#!/usr/bin/perl

my $installed = 0;
open( PERL, '<', '/usr/bin/perl' );
while (<PERL>) {
    if (/cPanel Perl Wrapper ([\d\.]+)/) {
        $ver       = $1;
        $installed = 1;
        last();
    }
}
close(PERL);
print "$installed";
