//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/_sshkey_selection.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/_sshkey_selection-sv.js
// Module:    /js2/_sshkey_selection-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Checking connection …":"Kontrollerar anslutningen …","No SSH key has been selected.":"Ingen SSH-nyckel har valts.","Root Password:":"Rotlösenord:","There is no SSH server listening on “[_1]”: [_2]":"Det är ingen SSH-server som lyssnar på ”[_1]”: [_2]","Unknown error; No error sent.":"Okänt fel. Inget fel skickades.","You must specify a host name or IP address.":"Du måste ange ett värdnamn eller en IP-adress.","You must specify a port number.":"Du måste ange ett portnummer.","You must specify a user name.":"Du måste ange ett användarnamn.","You must specify the key phrase for the selected SSH Key.":"Du måste ange nyckelfrasen för den valda SSH-nyckeln.","You must specify the password for your login.":"Du måste ange lösenordet för inloggningen.","You must specify the root password for “su” access.":"Du måste ange rotlösenordet för ”su”-åtkomst.","“[_1]” Password:":"”[_1]” Lösenord:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
