//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/addipform.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/addipform-ja.js
// Module:    /js2/addipform-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Adding IP range …":"IP アドレス範囲を追加中 …","Adding IP …":"IP アドレスを追加中 …","All excluded IP addresses and IP ranges must be valid and within the given IP range.":"除外 IP アドレスと IP アドレス範囲は全て、与えられた IP アドレス範囲の中で有効である必要があります。","Excluded IP Addresses/Ranges":"除外された IP アドレス/範囲","IP Address/Range":"IP アドレス/範囲","Success!":"成功！","The given IP address or range is invalid.":"所定のIPアドレスまたは範囲が無効です。","The given IP range does not fit within the given subnet mask.":"所定のIP範囲が、所定のサブネットマスク内に収まりません。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
