//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/edituser.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/edituser-nl.js
// Module:    /js2/edituser-nl
// Locale:    nl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A username cannot be longer than [quant,_1,character,characters].":"Een gebruikersnaam mag niet langer zijn dan [quant,_1,teken,tekens].","A username cannot have spaces.":"A username cannot have spaces.","A username cannot start with a number.":"Een gebruikersnaam kan niet met een getal beginnen.","A username must only contain lowercase alphanumeric characters.":"A username must only contain lowercase alphanumeric characters.","Contact Email":"Contacte-mail","Domain":"Domein","It is dangerous to change the account’s primary domain to one that already has data associated with it.":"It is dangerous to change the account’s primary domain to one that already has data associated with it.","Max Team Users with Roles":"Max Team Users with Roles","Saving non-package values …":"Niet-pakketwaarden opslaan…","Success!":"Geslaagd.","Username":"Gebruikersnaam","Usernames may not contain underscores.":"Usernames may not contain underscores.","You must provide one or two valid contact emails.":"You must provide one or two valid contact emails."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
