//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/edituser.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/edituser-ja.js
// Module:    /js2/edituser-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A username cannot be longer than [quant,_1,character,characters].":"ユーザー名は、[quant,_1,文字,文字]を超えてはいけません。","A username cannot have spaces.":"ユーザー名にスペースは使用できません。","A username cannot start with a number.":"ユーザー名の最初に数字を使用することはできません。","A username must only contain lowercase alphanumeric characters.":"ユーザー名に使用できる英数字は小文字のみです。","Contact Email":"連絡先メール","Domain":"ドメイン","It is dangerous to change the account’s primary domain to one that already has data associated with it.":"アカウントのプライマリドメインを既に関連するデータを持つものに変更すると、予期せぬ影響が出る可能性があります。","Max Team Users with Roles":"Max Team Users with Roles","Saving non-package values …":"非パッケージの値として保存中 …","Success!":"成功！","Username":"ユーザーネーム","Usernames may not contain underscores.":"ユーザーネームにアンダーバーは使用できません。","You must provide one or two valid contact emails.":"1つか2つの有効なメールアドレスを指定する必要があります。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
