//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/managehooks.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/managehooks-ar.js
// Module:    /js2/managehooks-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"الإغلاق","Delete a Hook":"حذف موضع الإضافة","Deleting hook …":"جارٍ حذف موضع الإضافة…","Disable":"تعطيل","Disabling hook …":"جارٍ تعطيل موضع إضافة في الروتين…","Enable":"تمكين","Enabling hook …":"جارٍ تفعيل موضع الإضافة في الروتين…","Move this hook down.":"قم بنقل موضع الإضافة هذا إلى الأسفل.","Move this hook to the bottom.":"قم بنقل موضع الإضافة هذا إلى الأسفل.","Move this hook to the top.":"قم بنقل موضع الإضافة هذا إلى الأعلى.","Move this hook up.":"قم بنقل موضع الإضافة هذا إلى الأعلى.","Reordering hooks …":"جارٍ إعادة ترتيب مواضع الإضافة…","Save":"حفظ","Saving …":"جارٍ الحفظ…","This hook is disabled.":"تم تعطيل موضع الإضافة.","This hook is enabled.":"تم تمكين موضع الإضافة.","View/Edit Hook Details":"عرض/تحرير تفاصيل موضع الإضافة"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
