//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/managehooks.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/managehooks-it.js
// Module:    /js2/managehooks-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"Chiudi","Delete a Hook":"Eliminare un hook","Deleting hook …":"Eliminazione hook in corso…","Disable":"Disattiva","Disabling hook …":"Disattivazione hook in corso…","Enable":"Attiva","Enabling hook …":"Attivazione hook in corso…","Move this hook down.":"Spostare questo hook verso il basso.","Move this hook to the bottom.":"Spostare questo hook nella parte inferiore.","Move this hook to the top.":"Spostare questo hook nella parte superiore.","Move this hook up.":"Spostare questo hook verso l’alto.","Reordering hooks …":"Riordinamento hook in corso…","Save":"Salva","Saving …":"Salvataggio in corso…","This hook is disabled.":"Hook disattivato.","This hook is enabled.":"Hook attivato.","View/Edit Hook Details":"Visualizza/modifica dettagli hook"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
