//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/minpwstrength.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/minpwstrength-en.js
// Module:    /js2/minpwstrength-en
// Locale:    en
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Saving …":"Saving …","Success!":"Success!","The password strength must be at least [numf,_1].":"The password strength must be at least [numf,_1].","You should verify that your connection to the server is stable, that a firewall does not block your request, and the [asis, cpsrvd] service is running.":"You should verify that your connection to the server is stable, that a firewall does not block your request, and the [asis, cpsrvd] service is running.","[output,strong,An error occurred while saving configuration]":"[output,strong,An error occurred while saving configuration]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
