//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/norootcopy.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/norootcopy-ms.js
// Module:    /js2/norootcopy-ms
// Locale:    ms
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Host":"Hos","You must input a valid fully qualified domain name or IP address.":"Anda mesti memasukkan nama domain atau alamat IP yang layak sepenuhnya yang sah.","You must provide a fully qualified domain name or IP address.":"Anda mesti memberikan nama domain atau alamat IP berkelayakan lengkap."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
