//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/restorefullbackup.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/restorefullbackup-he.js
// Module:    /js2/restorefullbackup-he
// Locale:    he
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"No filepath associated with username.":"אין נתיב קובץ המשויך לשם המשתמש.","No matching files were found.":"לא נמצאו קבצים תואמים.","None":"ללא","Restore File":"שחזר קובץ","Unable to get retrieve list of files, please try again later.":"לא ניתן להשיג רשימת אחזור של קבצים, נסה שוב מאוחר יותר.","User Name":"שם משתמש","You must choose a valid username.":"עליך לבחור שם משתמש חוקי.","You must provide a file.":"עליך לספק קובץ.","You must provide a username.":"עליך לספק שם משתמש."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
