//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/restorefullbackup.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/restorefullbackup-sv.js
// Module:    /js2/restorefullbackup-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"No filepath associated with username.":"Ingen filsökväg är associerad med användarnamnet.","No matching files were found.":"Inga matchande filer hittades.","None":"Ingen","Restore File":"Återställ fil","Unable to get retrieve list of files, please try again later.":"Det går inte att hämta listan med filer. Försök igen senare.","User Name":"Användarnamn","You must choose a valid username.":"Du måste välja ett giltigt användarnamn.","You must provide a file.":"Du måste ange en fil.","You must provide a username.":"Du måste ange ett användarnamn."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
