//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/transfer_session.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/transfer_session-hu.js
// Module:    /js2/transfer_session-hu
// Locale:    hu
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Abort":"Megszakítás","Abort Session Processing":"Munkamenet feldolgozásának megszakítása","Aborting …":"Megszakítás…","Alert":"Figyelmeztetés","Confirm":"Megerősítés","Loading …":"Betöltés…","OK":"OK","Pause":"Szüneteltetés","Pausing queue processing …":"Sor feldolgozásának szüneteltetése…","Pausing …":"Szüneteltetés…","Resume":"Folytatás","The system will abort any transfer processes as soon as possible. In order to prevent data loss, the system will complete ongoing restore operations before the entire session aborts.":"A rendszer a lehető legrövidebb időn belül megszakít minden átviteli folyamatot. Az adatvesztés elkerülése érdekében a rendszer a teljes munkamenet megszakítása előtt befejezi a folyamatban levő műveleteket.","The system will not add new items to the queue until you choose to resume. In order to prevent data loss, the system will complete ongoing operations.":"A rendszer nem ad új elemeket a sorhoz, amíg Ön a folytatás mellett nem dönt. Az adatvesztés elkerülése érdekében a rendszer befejezi a folyamatban levő műveleteket."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
