//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/transfer_session.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/transfer_session-sv.js
// Module:    /js2/transfer_session-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Abort":"Avbryt","Abort Session Processing":"Avbryt sessionsbearbetning","Aborting …":"Avbryter …","Alert":"Avisering","Confirm":"Bekräfta","Loading …":"Läser in …","OK":"OK","Pause":"Pause","Pausing queue processing …":"Pausar köbearbetningen …","Pausing …":"Pausar…","Resume":"Återuppta","The system will abort any transfer processes as soon as possible. In order to prevent data loss, the system will complete ongoing restore operations before the entire session aborts.":"Systemet kommer att avbryta eventuella överföringsprocesser snarast möjligt. För att undvika dataförlust kommer systemet att slutföra pågående återställningsåtgärder innan hela sessionen avbryts.","The system will not add new items to the queue until you choose to resume. In order to prevent data loss, the system will complete ongoing operations.":"Inga nya objekt kommer att läggas till i kön förrän du väljer att fortsätta. För att undvika dataförlust kommer systemet att slutföra pågående åtgärder."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
