//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/js2/transfer_session.js
// Generated: /usr/local/cpanel/whostmgr/docroot/js2/transfer_session-el.js
// Module:    /js2/transfer_session-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Abort":"Ματαίωση","Abort Session Processing":"Ματαίωση επεξεργασίας περιόδου λειτουργίας","Aborting …":"Πραγματοποιείται ματαίωση…","Alert":"Ειδοποίηση","Confirm":"Επιβεβαίωση","Loading …":"Φόρτωση…","OK":"OK","Pause":"Παύση","Pausing queue processing …":"Παύση επεξεργασίας ουράς…","Pausing …":"Παύση…","Resume":"Συνέχεια","The system will abort any transfer processes as soon as possible. In order to prevent data loss, the system will complete ongoing restore operations before the entire session aborts.":"Το σύστημα θα ματαιώσει οποιεσδήποτε διαδικασίες μεταφοράς όσο το δυνατόν συντομότερα. Για να αποφευχθεί η απώλεια δεδομένων, το σύστημα θα ολοκληρώσει τις τρέχουσες λειτουργίες αποκατάστασης πριν ματαιωθεί ολόκληρη η περίοδος λειτουργίας.","The system will not add new items to the queue until you choose to resume. In order to prevent data loss, the system will complete ongoing operations.":"Το σύστημα δεν θα προσθέσει νέα αντικείμενα στην ουρά μέχρι να επιλέξετε τη συνέχεια. Για να αποφευχθεί η απώλεια δεδομένων, το σύστημα θα ολοκληρώσει τις τρέχουσες λειτουργίες."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
