//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/configController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/configController-pl.js
// Module:    /templates/hulkd/views/configController-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system disabled the [asis,UseDNS] setting for [asis,SSHD] in order to add IP addresses to the whitelist. You must restart SSH through the [output,url,_1,Restart SSH Server,_2] page to implement the change.":"System wyłączył ustawienie [asis,UseDNS] w przypadku serwera [asis,SSHD], aby dodać adresy IP do białej listy. Aby wprowadzić tę zmianę, musisz ponownie uruchomić serwer SSH za pośrednictwem strony [output,url,_1,Uruchom ponownie serwer SSH,_2].","The system successfully saved your [asis,cPHulk] configuration settings.":"System pomyślnie zapisał ustawienia konfiguracji demona [asis,cPHulk].","You changed the protection level of [asis,cPHulk]. Click Save to implement this change.":"Zmieniono poziom ochrony usługi [asis,cPHulk]. Aby zastosować tę zmianę, kliknij przycisk Zapisz."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
