//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/configController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/configController-ms.js
// Module:    /templates/hulkd/views/configController-ms
// Locale:    ms
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system disabled the [asis,UseDNS] setting for [asis,SSHD] in order to add IP addresses to the whitelist. You must restart SSH through the [output,url,_1,Restart SSH Server,_2] page to implement the change.":"Sistem melumpuhkan [asis,UseDNS] tetapan bagi [asis,SSHD] untuk menambah alamat IP kepada senarai putih. Anda mesti memulakan semula SSH melalui halaman [output,url,_1,Mula Semula Halaman SSH,_2] untuk melaksanakan perubahan tersebut.","The system successfully saved your [asis,cPHulk] configuration settings.":"Sistem berjaya menyimpan [asis,cPHulk] tetapan konfigurasi anda.","You changed the protection level of [asis,cPHulk]. Click Save to implement this change.":"You changed the protection level of [asis,cPHulk]. Click Save to implement this change."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
