//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/hulkdEnableController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/hulkdEnableController-ms.js
// Module:    /templates/hulkd/views/hulkdEnableController-ms
// Locale:    ms
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The status for [asis,cPHulk] has changed, possibly in another browser session.":"Status bagi [asis,cPHulk] telah berubah, mungkin dalam sesi pelayar lain.","The system disabled the [asis,UseDNS] setting for [asis,SSHD] in order to add IP addresses to the whitelist. You must restart SSH through the [output,url,_1,Restart SSH Server,_2] page to implement the change.":"Sistem melumpuhkan [asis,UseDNS] tetapan bagi [asis,SSHD] untuk menambah alamat IP kepada senarai putih. Anda mesti memulakan semula SSH melalui halaman [output,url,_1,Mula Semula Halaman SSH,_2] untuk melaksanakan perubahan tersebut.","[asis,cPHulk] is now disabled.":"[asis,cPHulk] sekarang dilumpuhkan.","[asis,cPHulk] is now enabled.":"[asis,cPHulk] sekarang didayakan."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
