//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/hulkdEnableController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/hulkdEnableController-id.js
// Module:    /templates/hulkd/views/hulkdEnableController-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The status for [asis,cPHulk] has changed, possibly in another browser session.":"Status [asis,cPHulk] telah berubah, kemungkinan terjadi di sesi browser lain.","The system disabled the [asis,UseDNS] setting for [asis,SSHD] in order to add IP addresses to the whitelist. You must restart SSH through the [output,url,_1,Restart SSH Server,_2] page to implement the change.":"Sistem menonaktifkan pengaturan [asis,UseDNS] untuk [asis,SSHD] guna menambahkan alamat IP ke daftar putih. Anda harus mengaktifkan ulang SSH melalui Server Aktifkan Ulang SSH [output,url,_1,halaman,_2] untuk mengimplementasi perubahan.","[asis,cPHulk] is now disabled.":"[asis,cPHulk] sekarang dinonaktifkan.","[asis,cPHulk] is now enabled.":"[asis,cPHulk] sekarang diaktifkan."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
