//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/hulkdWhitelistController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/hulkd/views/hulkdWhitelistController-zh.js
// Module:    /templates/hulkd/views/hulkdWhitelistController-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add to Whitelist":"添加到白名单","Click to delete “[_1]” from the whitelist.":"单击以从白名单中删除“[_1]”。","Click to edit the comment for “[_1]”.":"单击以编辑“[_1]”的备注。","Do you want to permanently delete [quant,_1,record,records] from the whitelist?":"是否要从白名单中永久删除 [quant,_1,条记录,条记录]?","Do you want to permanently delete “[_1]” from the whitelist?":"是否要从白名单中永久删除“[_1]”?","Some IP addresses were not added to the whitelist.":"一些 IP 地址未添加到白名单。","Some records failed to update.":"未能更新某些记录。","The system disabled the [asis,UseDNS] setting for [asis,SSHD] in order to add IP addresses to the whitelist. You must restart SSH through the [output,url,_1,Restart SSH Server,_2] page to implement the change.":"为了将 IP 地址添加到白名单，系统禁用了 [asis,SSHD] 的 [asis,UseDNS] 设置。 必须通过[output,url,_1,重新启动 SSH 服务器,_2]页面重新启动 SSH 才能实施此更改。","The system was unable to delete [quant,_1,record,records] from the whitelist.":"系统无法从白名单中删除 [quant,_1,条记录,条记录]。","You have deleted all records from the whitelist.":"您已从白名单中删除所有记录。","You have successfully added [quant,_1,IP address,IP addresses] to the whitelist.":"您已成功将 [quant,_1,个 IP 地址,个 IP 地址]添加到白名单。","You have successfully added “[_1]” to the whitelist.":"您已成功将“[_1]”添加到白名单。","You have successfully deleted [quant,_1,record,records] from the whitelist.":"您已成功从白名单中删除 [quant,_1,条记录,条记录]。","You have successfully deleted “[_1]” from the whitelist.":"您已成功从白名单中删除“[_1]”。","You have successfully updated the [numerate,_1,comment,comments] for [quant,_1,IP address,IP addresses].":"You have successfully updated the [numerate,_1,comment,comments] for [quant,_1,IP address,IP addresses].","You have successfully updated the comment for “[_1]”.":"已成功更新“[_1]”的注释。","Your current IP address “[_1]” is not on the whitelist.":"您当前的 IP 地址“[_1]”不在白名单中。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
