//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/tls_wizard_redirect/index.cmb.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/tls_wizard_redirect/index.cmb-fr.js
// Module:    /templates/tls_wizard_redirect/index.cmb-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Because no other providers are enabled, the system enabled the [asis,cPanel Store] provider.":"Le système a activé le fournisseur [asis,cPanel Store], car aucun autre fournisseur n’est activé.","Click to continue as the “[_1]” user and purchase an [asis,SSL] certificate.":"Cliquez pour continuer en tant qu’utilisateur « [_1] » et acheter un certificat [asis,SSL].","Displaying [numf,_1] to [numf,_2] out of [quant,_3,item,items]":"Affichage de [numf,_1] à [numf,_2] éléments sur [quant,_3,élément,éléments]","The system changed the theme for user “[_1]” to “[_2]”, with the “[asis,Retro]” style, to support this feature.":"The system changed the theme for user “[_1]” to “[_2]”, with the “[asis,Retro]” style, to support this feature.","The system enabled the [numerate,_1,feature,features] [list_and_quoted,_2] for the user “[_3]” to ensure access to the “[_4]”.":"Le système a activé [numerate,_1,la fonctionnalité,les fonctionnalités] [list_and_quoted,_2] pour l’utilisateur « [_3] » afin de garantir l’accès à « [_4] ».","The system failed to fetch the user’s account information because of the following error: [_1]":"Le système n’a pas pu lire les informations du compte utilisateur en raison de l’erreur suivante : [_1]","You cannot redirect to this account because it does not have theme support for this feature.":"Vous ne pouvez pas rediriger vers ce compte, car il ne prend pas en charge les thèmes de cette fonction.","[asis,SSL]/[asis,TLS] Wizard":"Assistant [asis,SSL]/[asis,TLS]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
