//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/tls_wizard_redirect/index.cmb.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/tls_wizard_redirect/index.cmb-en.js
// Module:    /templates/tls_wizard_redirect/index.cmb-en
// Locale:    en
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Because no other providers are enabled, the system enabled the [asis,cPanel Store] provider.":"Because no other providers are enabled, the system enabled the [asis,cPanel Store] provider.","Click to continue as the “[_1]” user and purchase an [asis,SSL] certificate.":"Click to continue as the “[_1]” user and purchase an [asis,SSL] certificate.","Displaying [numf,_1] to [numf,_2] out of [quant,_3,item,items]":"Displaying [numf,_1] to [numf,_2] out of [quant,_3,item,items]","The system changed the theme for user “[_1]” to “[_2]”, with the “[asis,Retro]” style, to support this feature.":"The system changed the theme for user “[_1]” to “[_2]”, with the “[asis,Retro]” style, to support this feature.","The system enabled the [numerate,_1,feature,features] [list_and_quoted,_2] for the user “[_3]” to ensure access to the “[_4]”.":"The system enabled the [numerate,_1,feature,features] [list_and_quoted,_2] for the user “[_3]” to ensure access to the “[_4]”.","The system failed to fetch the user’s account information because of the following error: [_1]":"The system failed to fetch the user’s account information because of the following error: [_1]","You cannot redirect to this account because it does not have theme support for this feature.":"You cannot redirect to this account because it does not have theme support for this feature.","[asis,SSL]/[asis,TLS] Wizard":"[asis,SSL]/[asis,TLS] Wizard"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
