//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/passenger/views/details.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/passenger/views/details-de.js
// Module:    /jupiter/passenger/views/details-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Edit":"Bearbeiten","Edit Your Application":"Anwendung bearbeiten","Register":"Registrieren","Register Your Application":"Anwendung registrieren","You can use this section of the interface to manage your custom applications.":"Auf dieser Seite können Sie Ihre benutzerdefinierten Anwendungen verwalten.","You can use this section of the interface to register a new application.":"In diesem Abschnitt der Seite können Sie eine neue Anwendung registrieren.","You must finish adding or editing environment variables first.":"Sie müssen zuerst den Vorgang zum Hinzufügen oder Bearbeiten der Umgebungsvariablen abschließen.","You successfully registered your application.":"Ihre Anwendung wurde registriert.","You successfully updated your application.":"Ihre Anwendung wurde aktualisiert.","Your application is incomplete or invalid.":"Ihre Anwendung ist unvollständig oder ungültig."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
