//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/passenger/views/details.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/passenger/views/details-ko.js
// Module:    /jupiter/passenger/views/details-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Edit":"편집","Edit Your Application":"Edit Your Application","Register":"Register","Register Your Application":"Register Your Application","You can use this section of the interface to manage your custom applications.":"You can use this section of the interface to manage your custom applications.","You can use this section of the interface to register a new application.":"You can use this section of the interface to register a new application.","You must finish adding or editing environment variables first.":"You must finish adding or editing environment variables first.","You successfully registered your application.":"You successfully registered your application.","You successfully updated your application.":"You successfully updated your application.","Your application is incomplete or invalid.":"Your application is incomplete or invalid."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
