//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/passenger/views/manage.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/passenger/views/manage-de.js
// Module:    /jupiter/passenger/views/manage-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Are you sure that you want to unregister your application (“[_1]”)?":"Are you sure that you want to unregister your application (“[_1]”)?","Ensuring dependencies for your application …":"Abhängigkeiten Ihrer Anwendung werden sichergestellt…","The system couldn’t ensure dependencies for your application. For more information, see the instructions below.":"Das System konnte keine Abhängigkeiten für Ihre Anwendung sicherstellen. Weitere Informationen finden Sie in den folgenden Anweisungen.","The system ensured the dependencies for your application.":"Abhängigkeiten Ihrer Anwendung wurden sichergestellt.","The system queued your application to ensure its dependencies …":"Ihre Anwendung wurde in die Warteschlange aufgenommen, um die Abhängigkeiten sicherzustellen…","You can’t have more than [numf,_1] applications on your account.":"You can’t have more than [numf,_1] applications on your account.","You successfully disabled your application.":"Ihre Anwendung wurde deaktiviert.","You successfully enabled your application.":"Ihre Anwendung wurde aktiviert.","You successfully unregistered your application.":"Die Registrierung Ihrer Anwendung wurde aufgehoben."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
