//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/external_auth/services/ProvidersService.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/external_auth/services/ProvidersService-zh.js
// Module:    /templates/external_auth/services/ProvidersService-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system could not disable the “[_1]” provider in “[_2]”. The following error occurred: [_3]":"系统无法禁用“[_2]”中的“[_1]”提供程序。 出现以下错误: [_3]","The system could not enable the “[_1]” provider in “[_2]”. The following error occurred: [_3]":"系统无法启用“[_2]”中的“[_1]”提供程序。 出现以下错误: [_3]","The system has successfully disabled the “[_1]” provider in “[_2]”.":"系统已成功禁用“[_2]”中的“[_1]”提供程序。","The system has successfully enabled the “[_1]” provider in “[_2]”.":"系统已经成功启用“[_1]”中的“[_2]”提供程序。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
