//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/easyapache4/views/customize.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/easyapache4/views/customize-uk.js
// Module:    /templates/easyapache4/views/customize-uk
// Locale:    uk
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Update [asis,EasyApache 4]":"Update [asis,EasyApache 4]","[asis,EasyApache 4] is up to date[comment,no punctuation due to usage]":"[asis,EasyApache 4] is up to date[comment,no punctuation due to usage]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
