//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/easyapache4/views/provision.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/easyapache4/views/provision-it.js
// Module:    /templates/easyapache4/views/provision-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Provision process finished.":"Processo di provisioning terminato.","Provision process started.":"Processo di provisioning avviato.","The provision process exited with errors. Please check the log for details.":"Processo di provisioning terminato con errori. Per informazioni dettagliate, controllare il registro.","The provision process is complete.":"Processo di provisioning completato."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
