//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/easyapache4/views/provision.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/easyapache4/views/provision-ja.js
// Module:    /templates/easyapache4/views/provision-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Provision process finished.":"プロビジョニングのプロセスが完了しました。","Provision process started.":"プロビジョニングのプロセスが開始しました。","The provision process exited with errors. Please check the log for details.":"プロビジョニングのプロセスがエラーで終了しました。詳細はログをご確認ください。","The provision process is complete.":"プロビジョニングのプロセスが完了しました。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
