//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/external_auth/manage.cmb.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/external_auth/manage.cmb-es.js
// Module:    /templates/external_auth/manage.cmb-es
// Locale:    es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Status ([_1])":"Estado ([_1])","The system could not disable the “[_1]” provider in “[_2]”. The following error occurred: [_3]":"El sistema no pudo deshabilitar el proveedor “[_1]” en “[_2]”. Ocurrió el siguiente error: [_3]","The system could not enable the “[_1]” provider in “[_2]”. The following error occurred: [_3]":"El sistema no pudo habilitar al proveedor “[_1]” en “[_2]”. Ocurrió el siguiente error: [_3]","The system could not remove the “[_1] ([_2])” authentication linkage for “[_3]” due to an error: [_4]":"El sistema no pudo eliminar la vinculación de autenticación “[_1] ([_2])” de “[_3]” debido a que se produjo un error: [_4].","The system could not update the configurations for “[_1].” The following error occurred: “[_2]”":"The system could not update the configurations for “[_1].” The following error occurred: “[_2]”","The system encountered an error while it tried to retrieve the providers: [_1]":"Surgió un error en el sistema cuando este intentaba recuperar los proveedores: [_1]","The system encountered an error while it tried to retrieve the users: [_1]":"Surgió un error en el sistema cuando este intentaba recuperar los usuarios: [_1]","The system has removed the “[_1] ([_2])” authentication linkage for “[_3].”":"El sistema eliminó el vínculo de autenticación “[_1] ([_2])” para “[_3].”","The system has successfully disabled the “[_1]” provider in “[_2]”.":"El sistema deshabilitó correctamente al proveedor “[_1]” en “[_2]”.","The system has successfully enabled the “[_1]” provider in “[_2]”.":"El sistema habilitó correctamente el proveedor “[_1]” en “[_2]”.","The system successfully updated the configurations for “[_1].”":"The system successfully updated the configurations for “[_1].”"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
