//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/spamd/spamdconf.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/spamd/spamdconf-el.js
// Module:    /templates/spamd/spamdconf-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Attempting to save Spamd startup configuration.":"Προσπάθεια αποθήκευσης της διαμόρφωσης εκκίνησης Spamd.","Spamd startup configuration not updated: [_1]":"Η διαμόρφωση εκκίνησης Spamd δεν ενημερώθηκε: [_1]","Spamd startup configuration successfully updated.":"Η διαμόρφωση εκκίνησης Spamd ενημερώθηκε με επιτυχία."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
