//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/contact_manager/controllers/mainController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/contact_manager/controllers/mainController-pt_br.js
// Module:    /templates/contact_manager/controllers/mainController-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Click to continue as the “[_1]” user and modify the [asis,cPanel] notification settings.":"Clique para continuar como usuário “[_1]” e modifique as configurações de notificação [asis,cPanel].","Go to [asis,cPanel]":"Acesse o [asis,cPanel]","The system sent the [_1] notification message “[_2]” successfully to “[_3]”.":"O sistema enviou a mensagem de notificação [_1] “[_2]” com sucesso para “[_3]”.","The system sent the [_1] notification message “[_2]” successfully.":"O sistema enviou a mensagem de notificação [_1] “[_2]” com sucesso.","The system was unable to send the [_1] notification because of the following error: [_2]":"O sistema não conseguiu enviar a notificação [_1] devido ao seguinte erro: [_2]","The system was unable to send the [_1] notification to “[_2]” because of the following error: [_3]":"O sistema não conseguiu enviar a notificação [_1] para “[_2]” devido ao seguinte erro: [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
