//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/disablePromptController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/disablePromptController-ja.js
// Module:    /templates/twofactorauth/views/disablePromptController-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Are you sure you want to remove two-factor authentication for [quant,_1,user,users]?":"“[quant,_1,人のユーザー,人のユーザー]” の 2 要素認証を削除しますか?","Are you sure you want to remove two-factor authentication for “[_1]”?":"「[_1]」の二段階認証を削除しますか？","Do you want to remove two-factor authentication for all users?":"全てのユーザーから二段階認証を削除しますか？"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
