//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/disablePromptController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/disablePromptController-zh.js
// Module:    /templates/twofactorauth/views/disablePromptController-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Are you sure you want to remove two-factor authentication for [quant,_1,user,users]?":"是否确定要删除 [quant,_1,个用户,个用户]的双因素身份验证?","Are you sure you want to remove two-factor authentication for “[_1]”?":"是否确定要删除“[_1]”的双因素身份验证?","Do you want to remove two-factor authentication for all users?":"是否要删除所有用户的双因素身份验证?"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
