//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/enableController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/enableController-ar.js
// Module:    /templates/twofactorauth/views/enableController-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The Two-Factor Authentication security policy is now disabled.":"تم تعطيل نهج أمان المصادقة الثنائية حاليًا.","The Two-Factor Authentication security policy is now enabled.":"تم تمكين نهج أمان المصادقة الثنائية حاليًا.","The status for Two-Factor Authentication has changed, possibly in another browser session.":"تم تغيير الحالة للمصادقة الثنائية، من المحتمل في جلسة مستعرض أخرى."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
