//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/enableController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/enableController-es.js
// Module:    /templates/twofactorauth/views/enableController-es
// Locale:    es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The Two-Factor Authentication security policy is now disabled.":"La política de seguridad de la autenticación de dos factores está ahora deshabilitada.","The Two-Factor Authentication security policy is now enabled.":"La política de seguridad de autenticación de dos factores está ahora habilitada.","The status for Two-Factor Authentication has changed, possibly in another browser session.":"El estado para la autenticación de dos factores cambió, posiblemente en otra sesión del navegador."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
