//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/setupController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/twofactorauth/views/setupController-fr.js
// Module:    /templates/twofactorauth/views/setupController-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system failed to remove two-factor authentication for “[_1]”.":"Le système n’a pas pu supprimer l’authentification à deux facteurs pour « [_1] ».","The system successfully removed two-factor authentication for “[_1]”.":"Le système a supprimé l’authentification à deux facteurs pour « [_1] ».","[output,strong,Success:] Two-factor authentication is now configured on your account.":"[output,strong,Succès :] l’authentification à deux facteurs est désormais configurée sur votre compte."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
