//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/support/create_support_ticket/views/processingController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/support/create_support_ticket/views/processingController-ja.js
// Module:    /templates/support/create_support_ticket/views/processingController-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Host Access Control":"ホストのアクセス制御","The following non-fatal [numerate,_1,error,errors] occurred while allowing [asis,cPanel] support access to this server:":"The following non-fatal [numerate,_1,error,errors] occurred while allowing [asis,cPanel] support access to this server:","The system failed to add whitelist rules for “[_1]” while configuring access for [asis,cPanel] support.":"[asis,cPanel]サポートのアクセスを設定する際、システムは「[_1]」のホワイトリストルールを追加することに失敗しました。","The system failed to authorize access to the server with following error: [_1]":"以下のエラーで、システムがサーバへのアクセス認証に失敗しました：[_1]","The system failed to create a stub ticket with the following error: [_1]":"以下のエラーで、システムはスタブチケットの作成に失敗しました：[_1]","The system failed to initiate an [asis,SSH] connection test for this server: [_1]":"The system failed to initiate an [asis,SSH] connection test for this server: [_1]","The system failed to log agreement to the Technical Support Agreement with the following error: [_1]":"以下のエラーで、システムは契約をテクニカルサポート契約にログすることに失敗しました：[_1]","The system failed to process your request because of an error: [_1]":"エラーにより、システムはリクエストの処理に失敗しました：[_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
