//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/zone_editor/directives/naptr_validators.js
// Generated: /usr/local/cpanel/base/sharedjs/zone_editor/directives/naptr_validators-es_es.js
// Module:    legacy_shared/zone_editor/directives/naptr_validators-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Each “rs” value (the value after ‘+’ symbols) must contain only case insensitive letters a-z, digits 0-9, ‘-’s and ‘+’s. It must not exceed 32 characters.":"Cada valor “rs” (el valor que aparece detrás de los símbolos ‘+’) solo debe incluir letras de la A a la Z en mayúsculas y minúsculas, dígitos del 0 al 9, ‘-’s y ‘+’s. Este no puede estar formado por más de 32 caracteres.","Service must start with a letter.":"El servicio debe empezar con una letra.","To separate regular and replacement expressions, you must enter the delimiter before, between, and after the expressions. For example, delim-char regex delim-char replacement delim-char.":"Para separar expresiones regulares y de reemplazo, indique el delimitador antes, entre y detrás de las expresiones. Por ejemplo, delim-char regex delim-char replacement delim-char.","You can not use a digit or the flag character ‘i’ as your delimiter.":"No puede usar un dígito o el carácter de marca [output,apos]i[output,apos] como su delimitador.","“Protocol”, the first part of the service field must contain only case insensitive letters a-z, digits 0-9, ‘-’s and ‘+’s. It must not exceed 32 characters.":"“Protocolo”, la primera parte del campo de servicio, solo debe incluir letras a-z que no distingan entre mayúsculas y minúsculas, dígitos 0-9, ‘-’s y ‘+’s. Asimismo, no debe estar formado por más de 32 caracteres."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
