//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/accounts/createacct.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/accounts/createacct-el.js
// Module:    /templates/accounts/createacct-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A username cannot contain spaces.":"Το όνομα χρήστη δεν πρέπει να περιέχει κενά.","A username must have between [numf,_1] and [quant,_2,character,characters].":"Το όνομα χρήστη πρέπει να περιλαμβάνει από [numf,_1] έως [quant,_2,χαρακτήρα,χαρακτήρες] χαρακτήρες.","A username must start with a letter.":"A username must start with a letter.","Domain":"Τομέας","Email":"e-mail","Enable Spam Box":"Ενεργοποίηση Spam Box","Enter a nonnegative integer.":"Enter a nonnegative integer.","Enter an integer from [numf,_1] to [numf,_2].":"Enter an integer from [numf,_1] to [numf,_2].","Enter an integer no less than [numf,_1].":"Enter an integer no less than [numf,_1].","Package Name":"Όνομα πακέτου","Selected Package":"Επιλεγμένο πακέτο","The email field must be empty or an email address.":"Το πεδίο e-mail πρέπει να είναι κενό ή να είναι διεύθυνση e-mail.","The username cannot be the same as the password.":"Το όνομα χρήστη δεν μπορεί να είναι ίδιο με τον κωδικό πρόσβασης.","This is not a valid domain.":"Δεν είναι έγκυρος τομέας.","This is not a valid package name.":"Δεν είναι έγκυρο όνομα πακέτου.","This is not a valid username.":"Δεν είναι έγκυρο όνομα χρήστη.","Updating …":"Ενημέρωση…","Username":"Όνομα χρήστη","You must enable [asis,Apache SpamAssassin™] to use the Spam Box feature.":"You must enable [asis,Apache SpamAssassin™] to use the Spam Box feature.","You must select a package.":"Πρέπει να επιλέξετε πακέτο."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
