//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/accounts/createacct.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/accounts/createacct-nb.js
// Module:    /templates/accounts/createacct-nb
// Locale:    nb
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A username cannot contain spaces.":"Et brukernavn kan ikke inneholde mellomrom.","A username must have between [numf,_1] and [quant,_2,character,characters].":"Et brukernavn må ha mellom [numf,_1] og [quant,_2,tegn,tegn].","A username must start with a letter.":"A username must start with a letter.","Domain":"Domene","Email":"E-post","Enable Spam Box":"Aktiver Spam Box","Enter a nonnegative integer.":"Enter a nonnegative integer.","Enter an integer from [numf,_1] to [numf,_2].":"Enter an integer from [numf,_1] to [numf,_2].","Enter an integer no less than [numf,_1].":"Enter an integer no less than [numf,_1].","Package Name":"Pakkenavn","Selected Package":"Valgt pakke","The email field must be empty or an email address.":"E-postfeltet må være tomt, eller det må angis en e-postadresse.","The username cannot be the same as the password.":"Brukernavnet kan ikke være det samme som passordet.","This is not a valid domain.":"Dette er ikke et gyldig domene.","This is not a valid package name.":"Dette er ikke et gyldig pakkenavn.","This is not a valid username.":"Dette er ikke et gyldig brukernavn.","Updating …":"Oppdaterer …","Username":"Brukernavn","You must enable [asis,Apache SpamAssassin™] to use the Spam Box feature.":"You must enable [asis,Apache SpamAssassin™] to use the Spam Box feature.","You must select a package.":"Du må velge en pakke."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
