//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/zone_editor/index.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/zone_editor/index-ms.js
// Module:    /jupiter/zone_editor/index-ms
// Locale:    ms
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Domains":"Domain","Export":"Export","Generate":"Buatkan","Import":"Import","Manage Zone":"Manage Zone","Public [asis,DNSKEY]":"Public [asis,DNSKEY]","[asis,DS] Records":"[asis,DS] Records"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
