//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/cpanel_customization/views/jupiter/logoController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/cpanel_customization/views/jupiter/logoController-pt_br.js
// Module:    /templates/cpanel_customization/views/jupiter/logoController-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The current customization is invalid.":"A personalização atual é inválida.","The system failed to remove the logo.":"O sistema falhou em remover o logotipo.","The system failed to update your logos.":"O sistema falhou em atualizar seus logotipos.","The system is busy. Try again once the current operation is complete.":"O sistema está ocupado. Tente novamente assim que a operação atual for concluída.","The system successfully removed the logo.":"O sistema removeu com sucesso o logotipo.","The system successfully updated the logos.":"O sistema atualizou com sucesso os logotipos."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
