//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/setupcluster/page.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/setupcluster/page-pl.js
// Module:    /templates/setupcluster/page-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Delete entry for “[_1]”.":"Usuń wpis dotyczący „[_1]”.","Delete link to server “[output,strong,_1]”?":"Usunąć łącze do serwera „[output,strong,_1]”?","Edit key for “[_1]”.":"Edytuj klucz dla „[_1]”.","Link definition for server not updated.":"Nie zaktualizowano definicji łącza na serwerze.","Link definition for server, [output,strong,_1], not updated.":"Nie zaktualizowano definicji łącza na serwerze [output,strong,_1].","Link definition for server, [output,strong,_1], successfully updated.":"Zaktualizowano pomyślnie definicję łącza na serwerze [output,strong,_1].","Link to server, [output,strong,_1], successfully created.":"Utworzono pomyślnie łącze do serwera [output,strong,_1].","Link to server, [output,strong,_1], successfully deleted.":"Usunięto pomyślnie łącze do serwera [output,strong,_1].","Paste the replacement API token here. The current signature is: [_1]":"Paste the replacement API token here. The current signature is: [_1]","Paste the server’s API token here.":"Paste the server’s API token here.","The server name must be a valid host name or ip address.":"Nazwa serwera musi być prawidłową nazwą hosta lub adresem IP.","The server name, username, and API token are required.":"The server name, username, and API token are required.","The username can only include alphanumeric characters.":"Nazwa użytkownika może zawierać wyłącznie znaki alfanumeryczne.","Unable to create link to server “[output,strong,_1]”.":"Nie można utworzyć łącza do serwera „[output,strong,_1]”.","Unable to create link to server.":"Nie można utworzyć łącza do serwera.","Unable to delete link to server “[output,strong,_1]”.":"Nie można usunąć łącza do serwera „[output,strong,_1]”.","Unable to delete link to server.":"Nie można usunąć łącza do serwera.","You must specify both a username and an API token.":"You must specify both a username and an API token."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
