//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/setupcluster/page.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/setupcluster/page-zh_tw.js
// Module:    /templates/setupcluster/page-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Delete entry for “[_1]”.":"刪除“[_1]”的項目。","Delete link to server “[output,strong,_1]”?":"刪除與伺服器“[output,strong,_1]”的連結?","Edit key for “[_1]”.":"編輯“[_1]”的金鑰。","Link definition for server not updated.":"未更新伺服器的連結定義。","Link definition for server, [output,strong,_1], not updated.":"未更新伺服器 [output,strong,_1] 的連結定義。","Link definition for server, [output,strong,_1], successfully updated.":"已成功更新伺服器 [output,strong,_1] 的連結定義。","Link to server, [output,strong,_1], successfully created.":"已成功建立伺服器 [output,strong,_1] 的連結。","Link to server, [output,strong,_1], successfully deleted.":"已成功刪除伺服器 [output,strong,_1] 的連結。","Paste the replacement API token here. The current signature is: [_1]":"Paste the replacement API token here. The current signature is: [_1]","Paste the server’s API token here.":"Paste the server’s API token here.","The server name must be a valid host name or ip address.":"伺服器名稱必須是有效主機名稱或 IP 位址。","The server name, username, and API token are required.":"The server name, username, and API token are required.","The username can only include alphanumeric characters.":"使用者名稱只能包含英數字元。","Unable to create link to server “[output,strong,_1]”.":"無法建立伺服器“[output,strong,_1]”連結。","Unable to create link to server.":"無法建立伺服器連結。","Unable to delete link to server “[output,strong,_1]”.":"無法刪除伺服器“[output,strong,_1]”連結。","Unable to delete link to server.":"無法刪除伺服器連結。","You must specify both a username and an API token.":"You must specify both a username and an API token."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
