//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/setupcluster/page.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/setupcluster/page-ro.js
// Module:    /templates/setupcluster/page-ro
// Locale:    ro
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Delete entry for “[_1]”.":"Ştergeţi intrarea pentru „[_1]”.","Delete link to server “[output,strong,_1]”?":"Ştergeţi linkul către serverul „[output,strong,_1]”?","Edit key for “[_1]”.":"Editaţi cheia pentru „[_1]”.","Link definition for server not updated.":"Definiţia linkului pentru server nu este actualizată.","Link definition for server, [output,strong,_1], not updated.":"Definiţia linkului pentru server, [output,strong,_1], nu este actualizată.","Link definition for server, [output,strong,_1], successfully updated.":"Definiţia linkului pentru server, [output,strong,_1], este actualizată cu succes.","Link to server, [output,strong,_1], successfully created.":"Linkul către server, [output,strong,_1], a fost creat cu succes.","Link to server, [output,strong,_1], successfully deleted.":"Linkul către server, [output,strong,_1], a fost şters cu succes.","Paste the replacement API token here. The current signature is: [_1]":"Paste the replacement API token here. The current signature is: [_1]","Paste the server’s API token here.":"Paste the server’s API token here.","The server name must be a valid host name or ip address.":"Numele serverului trebuie să fie un nume de gazdă valid sau o adresă IP.","The server name, username, and API token are required.":"The server name, username, and API token are required.","The username can only include alphanumeric characters.":"Numele de utilizator pot include doar caractere alfanumerice.","Unable to create link to server “[output,strong,_1]”.":"Imposibil de creat link către server „[output,strong,_1]”.","Unable to create link to server.":"Imposibil de creat link către server.","Unable to delete link to server “[output,strong,_1]”.":"Imposibil de şters linkul către server „[output,strong,_1]”.","Unable to delete link to server.":"Imposibil de şters linkul către server.","You must specify both a username and an API token.":"You must specify both a username and an API token."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
