//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/setupcluster/page.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/setupcluster/page-fr.js
// Module:    /templates/setupcluster/page-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Delete entry for “[_1]”.":"Supprimer l’entrée pour « [_1] ».","Delete link to server “[output,strong,_1]”?":"Supprimer le lien au serveur « [output,strong,_1] » ?","Edit key for “[_1]”.":"Modifier la clé pour « [_1] ».","Link definition for server not updated.":"Définition de lien du serveur non mise à jour.","Link definition for server, [output,strong,_1], not updated.":"Définition de lien du serveur, [output,strong,_1], non mise à jour.","Link definition for server, [output,strong,_1], successfully updated.":"Définition de lien du serveur, [output,strong,_1], mise à jour.","Link to server, [output,strong,_1], successfully created.":"Le lien vers le serveur, [output,strong,_1], a été créé.","Link to server, [output,strong,_1], successfully deleted.":"Le lien vers le serveur, [output,strong,_1], a été supprimé.","Paste the replacement API token here. The current signature is: [_1]":"Paste the replacement API token here. The current signature is: [_1]","Paste the server’s API token here.":"Paste the server’s API token here.","The server name must be a valid host name or ip address.":"Le nom du serveur doit être un nom d’hôte ou une adresse IP valide.","The server name, username, and API token are required.":"The server name, username, and API token are required.","The username can only include alphanumeric characters.":"Le nom d’utilisateur ne peut inclure que des caractères alphanumériques.","Unable to create link to server “[output,strong,_1]”.":"Impossible de créer le lien vers le serveur « [output,strong,_1] ».","Unable to create link to server.":"Impossible de créer le lien vers le serveur.","Unable to delete link to server “[output,strong,_1]”.":"Impossible de supprimer le lien vers le serveur « [output,strong,_1] ».","Unable to delete link to server.":"Impossible de supprimer le lien au serveur.","You must specify both a username and an API token.":"You must specify both a username and an API token."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
