//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/market_provider_manager/views/editProductsController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/market_provider_manager/views/editProductsController-id.js
// Module:    /templates/market_provider_manager/views/editProductsController-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Clear the recommended product setting for this product group.":"Bersihkan pengaturan produk yang direkomendasikan untuk kelompok produk ini.","Editing the per-domain pricing for the product “[_1]”.":"Mengedit harga per-domain untuk produk “[_1]”.","Editing the per-wildcard-domain pricing for the product “[_1]”.":"Mengedit harga per-wildcard-domain untuk produk “[_1]”.","Enter a multiple of $[_1] USD.":"Masukkan beberapa $[_1] USD.","Make this the recommended product for its product group.":"Jadikan ini sebagai produk yang direkomendasikan untuk grup produknya.","The maximum price is $[_1] USD.":"Harga maksimumnya adalah $[_1] USD.","The minimum price is $[_1] USD.":"Harga minimumnya adalah $[_1] USD.","The system has successfully disabled the product “[_1]”.":"Sistem berhasil menonaktifkan produk “[_1]”.","The system has successfully enabled the product “[_1]”.":"Sistem berhasil mengaktifkan produk “[_1]”.","The system has successfully set the per-domain pricing for the product “[_1]” to $[_2].":"Sistem berhasil mengatur harga per domain untuk produk “[_1]” ke $[_2].","The system has successfully set the per-wildcard-domain pricing for the product “[_1]” to $[_2].":"Sistem berhasil mengatur harga per domain wildcard untuk produk “[_1]” ke $[_2].","“[_1]” is no longer recommended.":"“[_1]” tidak lagi disarankan.","“[_1]” is now recommended.":"“[_1]” sekarang direkomendasikan."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
