//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/cjt/ajaxapp.js
// Generated: /usr/local/cpanel/base/cjt/ajaxapp-sv.js
// Module:    legacy_cjt/ajaxapp-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"An unknown error occurred.":"Ett okänt fel inträffade.","Cancel":"Avbryt","Click to close.":"Klicka om du vill stänga.","Close":"Stäng","ERROR":"FEL","Error":"Fel","HTTP ERROR":"HTTP-fel","Notice":"Meddelande","OK":"OK","Proceed":"Fortsätt","Success!":"Klart."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
