//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/cjt/ajaxapp.js
// Generated: /usr/local/cpanel/base/cjt/ajaxapp-it.js
// Module:    legacy_cjt/ajaxapp-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"An unknown error occurred.":"Si è verificato un errore sconosciuto.","Cancel":"Annulla","Click to close.":"Fare clic per chiudere.","Close":"Chiudi","ERROR":"ERRORE","Error":"Errore","HTTP ERROR":"ERRORE HTTP","Notice":"Avviso","OK":"OK","Proceed":"Procedi","Success!":"Operazione completata"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
