//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/cjt/browser.js
// Generated: /usr/local/cpanel/base/cjt/browser-pt.js
// Module:    legacy_cjt/browser-pt
// Locale:    pt
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Load this page with a newer web browser. (You may need to use another device.)":"Load this page with a newer web browser. (You may need to use another device.)","Load this page with the latest available version for your platform of one of these web [numerate,_1,browser,browsers]: [join,~, ,_2]":"Load this page with the latest available version for your platform of one of these web [numerate,_1,browser,browsers]: [join,~, ,_2]","Try this page with the latest available version for your platform of “[_1]”":"Try this page with the latest available version for your platform of “[_1]”","Your web browser lacks support for a feature that this page requires.":"Your web browser lacks support for a feature that this page requires."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
