//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/transfers/TransferSessionUI.js
// Generated: /usr/local/cpanel/base/sharedjs/transfers/TransferSessionUI-zh.js
// Module:    legacy_shared/transfers/TransferSessionUI-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Abort":"中止","Aborted":"已中止","Aborting …":"正在中止…","Completed":"已完成","Failed":"失败","Local Restore Summary":"本地还原摘要","Pause Queue":"暂停队列","Paused":"已暂停","Pausing":"正在暂停","Pausing …":"正在暂停…","Pending":"挂起","Processing":"正在处理","Resume Queue":"恢复队列","Transfer from “[_1]” Summary":"从“[_1]”传输摘要"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
