//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/transfers/TransferMasterLogProcessor.js
// Generated: /usr/local/cpanel/base/sharedjs/transfers/TransferMasterLogProcessor-hu.js
// Module:    legacy_shared/transfers/TransferMasterLogProcessor-hu
// Locale:    hu
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Failed":"Sikertelen","Success":"Siker","View this restoration’s log.":"Helyreállítási napló megtekintése.","View this transfer’s log.":"Ennek az átviteli naplónak a megtekintése.","Warnings":"Figyelmeztetések","[_1]: “[_2]”":"[_1]: „[_2]”","[_1]: “[_2]” → “[_3]”":"[_1]: „[_2]” → „[_3]”"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
