//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/transfers/TransferSessionUI.js
// Generated: /usr/local/cpanel/base/sharedjs/transfers/TransferSessionUI-fi.js
// Module:    legacy_shared/transfers/TransferSessionUI-fi
// Locale:    fi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Abort":"Keskeytä","Aborted":"Keskeytetty","Aborting …":"Keskeytetään…","Completed":"Valmis","Failed":"Epäonnistui","Local Restore Summary":"Paikallinen palautusyhteenveto","Pause Queue":"Keskeytä jono","Paused":"Keskeytetty","Pausing":"Keskeytetään","Pausing …":"Keskeytetään…","Pending":"Odotustilassa","Processing":"Käsitellään","Resume Queue":"Jatka jonoa","Transfer from “[_1]” Summary":"Siirto kohteesta [_1] – yhteenveto"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
