<div>
    <div ng-show="alert.type === 'danger'" class='alert alert-danger ng-hide' role="alert">
        <button id="{{'btnClose_danger_' + alert.id}}" type='button'
            class='close' ng-if='alert.closeable' ng-click='runClose()' aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <button id="{{'btnMore_danger_' + alert.id}}" type='button'
            class='btn btn-more btn-link pull-right flip' ng-if='hasToggleHandler' ng-click='runToggleMore()'>{{moreLabel}}</button>
        <span class='glyphicon glyphicon-remove-sign' aria-hidden="true"></span>
        <div class='alert-message'>
            <strong class="alert-title" ng-show="errorLabel">{{errorLabel}}</strong>
            <span class="alert-body"><span id="{{'txtMessage_danger_' + alert.id}}" ng-bind-html="alert.message" ng-if="alert && alert.message"></span></span>
            <ul ng-if="alert.list && alert.list.length" class="alert-list">
                <li ng-repeat="value in alert.list">
                    <span id="{{'txtList_danger_' + alert.id + '_' + $index}}" ng-bind-html="value"></span>
                </li>
            </ul>
        </div>
    </div>

    <div ng-show="alert.type === 'info'" class='alert alert-info ng-hide' role="alert">
        <button id="{{'btnClose_info_' + alert.id}}" type='button'
            class='close' ng-if='alert.closeable' ng-click='runClose()' aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <button id="{{'btnMore_info_' + alert.id}}" type='button' class='btn btn-more btn-link pull-right flip' ng-if='hasToggleHandler' ng-click='runToggleMore()'>{{moreLabel}}</button>
        <span class='glyphicon glyphicon-info-sign' aria-hidden="true"></span>
        <div class='alert-message'>
            <strong class="alert-title" ng-show="infoLabel">{{infoLabel}}</strong>
            <span class="alert-body"><span id="{{'txtMessage_info_' + alert.id}}" ng-bind-html="alert.message" ng-if="alert && alert.message"></span></span>
            <ul ng-if="alert.list && alert.list.length" class="alert-list">
                <li ng-repeat="value in alert.list">
                    <span id="{{'txtList_info_' + alert.id + '_' + $index}}" ng-bind-html="value"></span>
                </li>
            </ul>
        </div>
    </div>

    <div ng-show="alert.type === 'success'" class='alert alert-success ng-hide' role="alert">
        <button id="{{'btnClose_success_' + alert.id}}" type='button'
            class='close' ng-if='alert.closeable' ng-click='runClose()' aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <button id="{{'btnMore_success_' + alert.id}}" type='button' class='btn btn-more btn-link pull-right flip' ng-if='hasToggleHandler' ng-click='runToggleMore()'>{{moreLabel}}</button>
        <span class='glyphicon glyphicon-ok-sign' aria-hidden="true"></span>
        <div class='alert-message'>
            <strong class="alert-title" ng-show="successLabel">{{successLabel}}</strong>
            <span class="alert-body"><span id="{{'txtMessage_success_' + alert.id}}" ng-bind-html="alert.message" ng-if="alert && alert.message"></span></span>
            <ul ng-if="alert.list && alert.list.length" class="alert-list">
                <li ng-repeat="value in alert.list">
                    <span id="{{'txtList_success_' + alert.id + '_' + $index}}" ng-bind-html="value"></span>
                </li>
            </ul>
        </div>
    </div>

    <div ng-show="alert.type === 'warning'" class='alert alert-warning ng-hide' role="alert">
        <button id="{{'btnClose_warning_' + alert.id}}" type='button'
            class='close' ng-if='alert.closeable' ng-click='runClose()' aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <button id="{{'btnMore_warning_' + alert.id}}" type='button' class='btn btn-more btn-link pull-right flip' ng-if='hasToggleHandler' ng-click='runToggleMore()'>{{moreLabel}}</button>
        <span class='glyphicon glyphicon-exclamation-sign' aria-hidden="true"></span>
        <div class='alert-message'>
            <strong class="alert-title" ng-show="warnLabel">{{warnLabel}}</strong>
            <span class="alert-body"><span id="{{'txtMessage_warning_' + alert.id}}" ng-bind-html="alert.message" ng-if="alert && alert.message"></span></span>
            <ul ng-if="alert.list && alert.list.length" class="alert-list">
                <li ng-repeat="value in alert.list">
                    <span id="{{'txtList_warning_' + alert.id + '_' + $index}}" ng-bind-html="value"></span>
                </li>
            </ul>
        </div>
    </div>
</div>