<div>
    <div class="alert-list-container" ng-class="[ getPositionClasses(), {
        'show-scroll-bar': needsScrollbar(),
    }]">
        <div class="alert-list"><!-- Used to get the full height of the list, since alert-list-container can be constrained -->
            <div class="alert-container" ng-repeat="alert in alerts"><!-- Used to smoothly animate the alert margins -->
                <cp:alert ng-model="alert"
                        id="{{ alert.id }}"
                        auto-close="alert.autoClose">
                </cp:alert>
            </div>
         </div>
     </div>
    <div class="alert-list-backdrop" ng-if="alertsPresent" ng-class="getPositionClasses()">
    </div>
</div>
