<ul class="breadcrumb">
    <li ng-repeat="breadcrumb in crumbs" ng-class="{'hidden-xs':!($last-1) && !$first}">
        <ng-switch on="$last">
            <span ng-switch-when="true"><span ng-bind-html="breadcrumb.name"></span></span>
            <a href="javascript:void(0)" ng-click="changeRoute(breadcrumb.path)" ng-switch-default>
                <i class="fas fa-chevron-left visible-xs-inline" ng-if="$last-1"></i>
                <span ng-bind-html="breadcrumb.name"></span>
            </a>
        </ng-switch>
    </li>
</ul>
