<span class="input-group bytes-input">
    <input type="number" id="{{name}}" name="{{name}}" class="form-control {{extraInputClasses}}" size="{{size}}" ng-model="inputValue"
        ng-model-options="{ debounce: 500 }"
        ng-disabled="isDisabled"
        min="{{min}}">
    <span class="input-group-btn" uib-dropdown>
        <button type="button" id="{{name}}DropDownButton" name="{{name}}DropDownButton" uib-dropdown-toggle class="btn btn-default dropdown-toggle" title="{{ selectedUnit.full }}"
            ng-disabled="isDisabled">
            {{ selectedUnit.abbr }}
            <span class="fas fa-caret-down"></span>
        </button>
        <ul uib-dropdown-menu role="menu" class="dropdown-menu">
            <li ng-repeat="(key, value) in units track by key">
                <a href="javascript:void(0)" ng-click="selectUnit(key)" title="{{value.full}}">{{ value.abbr }}</a>
            </li>
        </ul>
    </span>
</span>

