<div class="copy-field-directive">
    <div class="row">
        <div class="col-xs-12">
            <div class="input-group">
                <span class="input-group-addon"><strong ng-bind="label"></strong></span>

                <!--
                    Use an <input> when there is only one line
                    because a non-resizable, overflow-hidden <textarea>
                    doesn’t allow the user to see the full value.
                -->
                <input ng-if="!multilineRows || multilineRows < 2" readonly ng-value="text" placeholder="{{placeholderText}}" class="form-control copy-field-data" id="{{ :: copyFieldID }}" name="{{::parentID}}_recordField">

                <textarea ng-if="multilineRows && multilineRows > 1" placeholder="{{placeholderText}}" class="form-control multi-line copy-field-data" id="{{ :: copyFieldID }}" name="{{::parentID}}_recordField" readonly rows="{{multilineRows}}" ng-value="text" ng-bind="text"></textarea>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 text-right">
            <span ng-transclude></span>
            <a ng-click="text && copyToClipboard()" href="javascript:void(0)" class="btn btn-sm btn-link" ng-disabled="!text">
                <span ng-bind="copyLabel"></span>
                <i class="fas fa-copy" aria-hidden="true"></i>
            </a>
        </div>
    </div>
</div>
