<div class="date-picker-directive">
    <p class="input-group">
        <input
            id="{{parentID}}_datePicker_input"
            type="text"
            class="form-control"
            uib-datepicker-popup
            ng-model="selectedDate"
            is-open="showingPopup"
            ng-required="true"
            ng-change="onChange(selectedDate)"
            datepicker-options="options"
            current-text="{{::currentTextLabel}}"
            clear-text="{{::clearTextLabel}}"
            close-text="{{::closeTextLabel}}"  />

        <span class="input-group-btn">
            <button id="{{parentID}}_datePicker_btn" type="button" class="btn btn-default" ng-click="showPopup()">
                <i class="fas fa-calendar" aria-hidden="true"></i>
            </button>
        </span>
    </p>
</div>