<div class="growl-container" ng-class="wrapperClasses()">
    <div class="growl-item alert" id="{{ message.id }}" ng-repeat="message in growlMessages.directives[referenceId].messages" ng-class="alertClasses(message)" ng-click="stopTimeoutClose(message)">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true" ng-click="growlMessages.deleteMessage(message)" ng-show="!message.disableCloseButton">&times;</button>
        <button type="button" class="close" aria-hidden="true" ng-show="showCountDown(message)">{{message.countdown}}</button>
        <h4 class="growl-title" ng-show="message.title" ng-bind="message.title"></h4>
        <div class="growl_icon">
            <span class="glyphicon glyphicon-remove-sign" ng-if="message.severity == 'error'"></span>
            <span class="glyphicon glyphicon-exclamation-sign" ng-if="message.severity == 'warning' || message.severity == 'warn'"></span>
            <span class="glyphicon glyphicon-info-sign" ng-if="message.severity == 'info'"></span>
            <span class="glyphicon glyphicon-ok-sign" ng-if="message.severity == 'success'"></span>
        </div>
        <div class="growl-message" ng-bind-html="message.text"></div>
        <div class="growl_action" ng-show="message.variables.showAction">
            <button class="btn btn-primary btn-xs" ng-click="$eval(message.variables.action)">{{message.variables.buttonLabel}}</button>
        </div>
    </div>
</div>
