<span class="required-field"                       id="fieldRequired_{{fieldName}}" ng-show="showAsterisk()" title="{{ text('required') }}">*</span>
<span class="fas fa-check field-validation-valid"   id="fieldValid_{{fieldName}}"    ng-show="isValid()"      title="{{ text('valid') }}"></span>
<span class="fas fa-times field-validation-invalid" id="fieldInvalid_{{fieldName}}"  ng-show="isInvalid()"    title="{{ text('invalid') }}"></span>
<span glyph-class="fas fa-spinner"                  id="{{spinnerId}}"               spinner                  title="{{ text('validating') }}"></span>
