<div class="multi-field-editor-directive" id="{{ :: parentID }}_multiFieldEditor">
	<div class="form-group">
		<div class="row" ng-show="ngModel.length > 49">
			<div class="col-xs-12 col-md-12">
				<a href class="btn btn-link" ng-click="addRow()" id="{{ :: parentID }}_multiFieldEditor_addNewButton_top">
					<span class='glyphicon glyphicon-plus'></span>
					{{ :: addNewLabel }}
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-md-12">
				<div id="{{ :: parentID }}_multiFieldEditor_valueItems" class="mfe-items" ng-transclude></div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-md-12">
				<a href class="btn btn-link" ng-click="addRow()" id="{{ :: parentID }}_multiFieldEditor_addNewButton_bottom">
					<span class='glyphicon glyphicon-plus'></span>
					{{ :: addNewLabel }}
				</a>
			</div>
		</div>
	</div>
</div>
