<div>
    <div class="btn-group pageSizeButtons" role="group">
        <button type="button" id="{{size.id}}" ng-repeat="size in options" class="btn btn-default btn-sm no-validation-border" ng-class="{active: $parent.pageSize == '{{size.value}}'}" ng-model="$parent.pageSize" uib-btn-radio="{{size.value}}" aria-label="{{size.description}}" aria-pressed="{{ $parent.pageSize == size.value }}">{{size.label}}</button>
    </div>
</div>
