<div class="page-size">
    <div ng-hide="autoHide && options[0].value >= totalItems" class="form-group" >
        <label for="{{parentID}}_select" class="title">{{pageSizeTitle}}</label>
        <select id="{{parentID}}_select"
            class="form-control"
            ng-options="size.value as size.label for size in options"
            ng-model="pageSize">
        </select>
    </div>
</div>
