<quick-filters id="quickFilters" title="Filter" active="quickFilterValue" on-filter-change="fetch()">
    <quick-filter-item id="lnkFilterAll" value="all" title="Show all of my accounts.">All</quick-filter-item>
    <quick-filter-item id="lnkFilterRestricted" value="restricted" title="Show my restricted accounts.">Restricted</quick-filter-item>
    <quick-filter-item id="lnkFilterDefault" value="default" title="Show my system account.">System Account</quick-filter-item>
    <quick-filter-item id="lnkFilterOverQuota" value="overUsed" title="Show accounts that have used all of their storage space.">Exceeded Storage</quick-filter-item>
</quick-filters>
