<div class="input-group">
    <input type="text"
        id="{{parentID}}_input"
        class="form-control"
        placeholder="{{placeholder}}"
        title="{{title}}"
        ng-model="filterText"
        ng-model-options="modelOptions"
        ng-keyup="clear($event)"
        prevent-default-on-enter
        auto-focus="{{autofocus}}"
        aria-label="{{ariaLabelSearch}}"/>
    <span class="input-group-btn">
        <button id="{{parentID}}_submit_btn"
            class="btn btn-default"
            ng-click="filterText=''"
            type="button"
            ng-attr-aria-label="{{ !filterText ? ariaLabelSearch : ariaLabelClear }}">
            <span class="glyphicon"
                ng-class="{ 'glyphicon-search' : !filterText, 'glyphicon-remove' :filterText  }"
                aria-hidden="true">
            </span>
        </button>
    </span>
</div>
