<span class="cp-select-sort">
    <span>{{ label }}</span>
    <select id="select-sort-dropdown_{{ idSuffix }}"
            class="form-control"
            ng-model="sortMeta.sortBy"
            ng-options="fieldObj.field as fieldObj.label for fieldObj in sortFields"
            ng-change="sort()">
    </select>
    <i id="select-sort-direction_{{ idSuffix }}"
       class="btn btn-default"
       ng-class="{ true: 'icon-arrow-up', false: 'icon-arrow-down' }[getDir() == 'asc']"
       ng-click="sort(true)"
       ng-attr-title="{{ getTitle() }}">
    </i>
</span>
