<div class="stats-widget" ng-class="{'stats-warning': showWarning}">
    <div class="stats-widget-body">
        <div class="stats-item">
            <span id="{{availableID}}" class="stats-huge">{{availableValue}}</span>
            <span class="stats-title">{{availableTitle}}</span>
        </div>
        <div class="stats-item">
            <span id="{{usedID}}" class="stats-huge">{{usedValue}}</span>
            <span class="title">{{usedTitle}}</span>
        </div>
    </div>
    <div class="stats-widget-footer" ng-if="showUpgradeLink || showWarning">
        <a ng-click="showWarningDetails()"
            ng-if="showWarning"
            id="statsWarning"
            class="btn btn-sm btn-link"
            title="{{detailsTooltip}}">
            <i class="fas fa-exclamation-triangle"></i>
            {{viewDetailsText}}
        </a>
        <a id="{{upgradeLinkID}}" ng-href="{{upgradeLink}}"
            ng-if="showUpgradeLink && upgradeLink !== ''"
            id="statsUpgradeLink"
            class="btn btn-sm btn-link"
            target="{{upgradeLinkTarget}}"
            title="{{upgradeTooltip}}">
            {{upgradeLinkText}} <i class="far fa-arrow-alt-circle-right"></i>
        </a>
    </div>
</div>
