//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/libraries/cjt2/src/directives/terminal.js
// Generated: /usr/local/cpanel/share/libraries/cjt2/src/directives/terminal-pt_br.js
// Module:    cjt/directives/terminal-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Exit Code":"Código de Saída","Opening a connection …":"Abrindo uma conexão…","Reconnect":"Reconectar","The [asis,WebSocket] handshake failed at [local_datetime,_1,time_format_medium].":"The [asis,WebSocket] handshake failed at [local_datetime,_1,time_format_medium].","The connection to the server ended in failure at [local_datetime,_1,time_format_medium]. ([_2])":"The connection to the server ended in failure at [local_datetime,_1,time_format_medium]. ([_2])","Waiting for the terminal …":"Aguardando pelo terminal…"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
