<div class="cp-terminal">
    <div class="terminal-loading alert alert-info" ng-if="loading">
        <i class="fas fa-spinner fa-spin" aria-hidden="true"></i>
        <span class="terminal-opening" ng-if="opening">{{::openingString}}</span>
        <span class="terminal-waiting" ng-if="!opening">{{::waitingString}}</span>
    </div>

    <p ng-if="closed && !windowIsUnloading()">
        <button class="terminal-reconnect btn btn-primary" type="button" ng-click="connect()">{{::reconnectString}}</button>
    </p>

    <div class="terminal-container" ng-class="{ 'disabled': (closed || loading) }">
        <div class="terminal-title" ng-bind="title"></div>
        <div class="terminal-xterm"></div>
    </div>

    <div class="terminal-exitcode" ng-if="exitCode">{{::exitCodeString}}: {{exitCode}}</div>
</div>
