<div role="switch"
    class="cjt2-toggle-switch toggle-switch-wrapper"
    tabindex="0"
    aria-checked="{{ get_aria_value() }}"
    aria-label="{{ariaLabel}}"
    ng-click="toggle_status()"
    ng-keyup="handle_keyup($event)"
    ng-keydown="handle_keydown($event)"
    ng-class="{
        disabled: (changing_status || isDisabled),
        'switch-off': !ngModel,
        'switch-on': ngModel,
        'no-label': noLabel
    }">
    <spinner
        ng-if="!noSpinner && spinnerPosition === 'left'"
        id="{{spinnerId}}"
        glyph-class="fas fa-sync toggle-switch-updating-indicator toggle-switch-updating-indicator-left">
    </spinner>
    <span ng-if="labelPosition == 'left' && !changing_status" class="toggle-switch-label toggle-switch-label-left">
        {{ ngModel ? enabledLabel : disabledLabel}}
    </span>
    <div
        class="toggle-switch"
        ng-class="{disabled: (changing_status || isDisabled)}">
        <div id="{{parentID}}_toggle_visual" class="toggle-switch-animate" ng-class="{'switch-off': !ngModel, 'switch-on': ngModel}">
            <span class="switch-left"></span>
            <span class="knob"></span>
            <span class="switch-right"></span>
        </div>
    </div>
    <span ng-if="labelPosition == 'right' && !changing_status" class="toggle-switch-label toggle-switch-label-right">
        {{ ngModel ? enabledLabel : disabledLabel}}
    </span>
    <spinner
        ng-if="!noSpinner && spinnerPosition === 'right'"
        id="{{spinnerId}}"
        glyph-class="fas fa-sync toggle-switch-updating-indicator toggle-switch-updating-indicator-right">
    </spinner>
</div>
