<toggle-label-info
    id="lblDomain"
    for="ddlDomain"
    label-text="Domain">Additional information about domain</toggle-label-info>

<toggle-label-info
    id="lblEmail"
    for="txtEmail"
    label-text="Email Address"
    show-info-block="true">Additional information about email address</toggle-label-info>

<toggle-label-info
    id="lblIDVerification"
    label-id="lblVerification"
    info-icon-id="imgQuestionMark"
    info-block-id="infoBlockID"
    for="txtIDVerification"
    label-text="IDVerification"
    show-info-block="true">ID Verification</toggle-label-info>

<toggle-label-info
    id="lblToggleEvent"
    for="txtSomething"
    label-text="Blah"
    on-toggle="onToggle(show)">Barg</toggle-label-info>