<div class="toggle-info-label-container">
    <label id="{{labelID}}" for="{{for}}">
        {{labelText}}
        <label-suffix for="{{for}}" ng-if="includeLabelSuffix"></label-suffix>
    </label>
    <a id="{{infoIconID}}"
        href="javascript:void(0)"
        class="far fa-question-circle text-primary form-info-sign"
        ng-click="toggleInfoBlock()"
        title="{{toggleActionTitle}}">
    </a>

    <span id="{{infoBlockID}}" class="info-block" ng-transclude ng-show="showInfoBlock">
    </span>
</div>
