<form name="theFormStandard" id="theFormStandard">
    <input type="text" id="theTextStandard" name="theTextStandard" ng-model="mytext" required ng-pattern="/^[A-Za-z]+$/">
    <ul validation-container field-name="theTextStandard" role="alert">
        <li validation-item field-name="theTextStandard" validation-name="required" id="valTextRequired">
            Please enter some text
        </li>
        <li validation-item field-name="theTextStandard" validation-name="pattern" id="valTextPattern">
           Should only be alphabets
        </li>
    </ul>
</form>

<form name="theFormAuto" id="theFormAuto">
    <input type="text" id="theTextAuto" name="theTextAuto" ng-model="mytext" length="10">
    <ul validation-container field-name="theTextAuto" role="alert">
    </ul>
</form>

<form name="theFormManual" id="theFormManual">
    <input type="text" id="theTextManual" name="theTextManual" ng-model="mytext" min-length="3" max-length="5">
    <ul validation-container field-name="theTextManual" role="alert" manual>
        <li validation-item field-name="theTextManual" validation-name="minLength" id="valTextMinLength">
        </li>
        <li validation-item field-name="theTextManual" validation-name="maxLength" id="valTextMaxLength">
        </li>
    </ul>
</form>