<form name="theForm" id="theForm">
    <input type="text" id="theText" name="theText" ng-model="mytext" required ng-pattern="/^[A-Za-z]+$/">
    <ul validation-container field-name="theText" role="alert">
        <li validation-item field-name="theText" validation-name="required" id="valTextRequired">
            Please enter some text
        </li>
        <li validation-item field-name="theText" validation-name="pattern" id="valTextPattern">
           Should only be alphabets
        </li>
    </ul>
</form>

<form name="theFormNoIcon" id="theFormNoIcon">
    <style>
        .bullet::before {
            content: "•";
            padding-right: 10px;
            font-weight: bold;
            font-size: larger;
        }
    </style>
    <input type="text" id="theTextNoIcon" name="theTextNoIcon" ng-model="mytext" required>
    <ul validation-container field-name="theTextNoIcon" role="alert">
        <li validation-item field-name="theTextNoIcon" validation-name="required" id="valTextRequiredStandard">
            Standard
        </li>
        <li validation-item field-name="theTextNoIcon" validation-name="required" id="valTextRequiredNoIcon" no-icon>
            No Icon
        </li>
        <li validation-item field-name="theTextNoIcon" validation-name="required" id="valTextRequiredCustomIcon" no-icon prefix-class="bullet">
            Change Icon
        </li>
    </ul>
</form>