<ul class="validation-container ng-hide" ng-show="canShow()">
    <li class="validation validation-error" ng-repeat="message in aggregateMessages() track by message.id" ng-if="canShowItem(message.validatorName)">
        <i class="fas fa-exclamation-circle"></i>
        <span id="{{ message.id }}" class="validation-message">
            <span ng-bind-html="message.message"></span>
        </span>
    </li>
    <li ng-transclude></li>
</ul>
