//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/mail/spam/views/ROUTES.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/mail/spam/views/ROUTES-id.js
// Module:    /jupiter/mail/spam/views/ROUTES-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Adjust Spam Threshold Score":"Sesuaikan Skor Ambang Spam","Auto-Delete":"Hapus Otomatis","Automatically delete messages with spam scores that meet or exceed the Auto-Delete Threshold Score. The Auto-Delete Threshold Score does not affect the Spam Threshold Score.":"Otomatis hapus pesan dengan skor spam yang memenuhi atau melampaui Skor Ambang Hapus Otomatis. Skor Ambang Hapus Otomatis tidak memengaruhi Skor Ambang Spam.","Blacklist":"Daftar Blokir","Calculated Spam Score Settings":"Pengaturan Skor Spam Terhitung","Configure the [asis,Spam Score Threshold].":"Konfigurasi [asis,Ambang Skor Spam].","Configure the blacklist settings for Spam Filters.":"Konfigurasi pengaturan daftar blokir untuk Filter Spam.","Configure the calculated spam score settings.":"Konfigurasi pengaturan skor spam terhitung.","Configure the whitelist settings for Spam Filters.":"Konfigurasi pengaturan daftar yang diizinkan untuk Filter Spam.","If your hosting provider enables rewrites, the server will add a “***SPAM***” tag to the subject when the message’s calculated spam score meets or exceeds the Spam Threshold Score.":"Jika penyedia hosting Anda mengaktifkan penulisan ulang, server akan menambahkan tag [output,quot]***SPAM***[output,quot] ke subjek saat skor spam yang dihitung pada pesan memenuhi atau melampaui Skor Ambang Spam.","Overview":"Tinjauan","Spam Box":"Kotak Spam","Spam Box will deliver any emails that the system identifies as spam into a separate mail folder named [output,em,spam].":"Kotak Spam akan mengirimkan email apa pun yang diidentifikasi sebagai spam oleh sistem ke folder bernama [output,em,spam].","Whitelist":"Daftar yang Diizinkan"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
