//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/greylist/views/base.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/greylist/views/base-ar.js
// Module:    /templates/greylist/views/base-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add to Trusted Hosts":"إضافة إلى المضيفات الموثوقة","Some Host [asis,IP] addresses were not added to the Trusted Hosts list.":"لم تتم إضافة بعض عناوين مضيف [asis,IP] إلى قائمة المضيفات الموثوقة.","The status for [asis,Greylisting] has changed, possibly in another browser session.":"تم تغيير الحالة لـ [asis,Greylisting] من المحتمل في جلسة مستعرض أخرى.","You have successfully added [quant,_1,record,records] to the Trusted Hosts list.":"لقد قمت بنجاح بإضافة [quant,_1,سجلاً,سجلات ] إلى قائمة المضيفات الموثوقة.","You have successfully added “[_1]” to the Trusted Hosts list.":"لقد قمت بنجاح بإضافة “[_1]” إلى قائمة المضيفات الموثوقة.","You have successfully updated the comment for “[_1]”.":"لقد قمت بتحديث الأمر لـ “[_1]” بنجاح.","Your neighboring [asis,IP] addresses are not in the Trusted Hosts list.":"العناوين [asis,IP] المجاورة غير موجودة في قائمة المضيفات الموثوقة.","[asis,Exim] is disabled on the server which makes [asis,Greylisting] ineffective. Use the [output,url,_1,Service Manager page,_2] to enable [asis,Exim].":"تم تعطيل [asis,Exim] على الخادم مما أدى إلى إيقاف فاعلية [asis,Greylisting]. استخدم [output,url,_1,صفحة إدارة الخدمة,_2] لتمكين [asis,Exim].","[asis,Greylisting] is now disabled.":"[asis,Greylisting] معطل حاليًا.","[asis,Greylisting] is now enabled.":"تم تمكين [asis,Greylisting] حاليًا."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
