//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/greylist/views/config.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/greylist/views/config-sv.js
// Module:    /templates/greylist/views/config-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The number of minutes during which the mail server accepts a resent email from an unknown triplet.":"Antalet minuter som e-postservern accepterar ett återsänt e-postmeddelande från en okänd trippel.","The number of minutes during which the mail server defers email from an unknown triplet.":"Antalet minuter som e-postservern fördröjer e-post från en okänd trippel.","The system successfully saved your [asis,Greylisting] configuration settings.":"Dina [asis,Greylisting]-konfigurationsinställningar har sparats.","The time at which the mail server treats a resent email as coming from a new, unknown triplet.":"Den tid då e-postservern behandlar ett återsänt e-postmeddelande som om det kommer från en ny, okänd trippel.","Whether the system automatically accepts email from hosts with a valid [asis,SPF] record.[comment,this text is used in a tooltip]":"Huruvida systemet automatiskt accepterar e-post från värdar med en giltig [asis,SPF]-post.[comment,this text is used in a tooltip]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
