//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/apps/mailinglists/services/mailingListsService.js
// Generated: /usr/local/cpanel/share/apps/mailinglists/services/mailingListsService-hu.js
// Module:    shared/mailinglists/services/mailingListsService-hu
// Locale:    hu
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"[join,_1,_2][_1] … and [numf,_3] more":"[join,_1,_2][_1] … és további [numf,_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
