//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/email_accounts/decorators/paginationDecorator.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/email_accounts/decorators/paginationDecorator-ja.js
// Module:    /jupiter/email_accounts/decorators/paginationDecorator-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Go to first page.":"最初のページに移動します。","Go to last page.":"最後のページに移動します。","Go to next page.":"次のページに進みます。","Go to page “[_1]”.":"「[_1]」ページに進みます。","Go to previous page.":"前のページに戻ります。","Page [numf,_1] of [numf,_2]":"ページ [numf,_1]/[numf,_2]","Pagination":"ページ付け"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
