//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/backup_configuration/views/config.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/backup_configuration/views/config-ko.js
// Module:    /templates/backup_configuration/views/config-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Friday":"금요일","Monday":"월요일","Saturday":"토요일","Sunday":"일요일","The system successfully saved the backup configuration.":"The system successfully saved the backup configuration.","Thursday":"목요일","Tuesday":"화요일","Wednesday":"수요일"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
