//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/backup_configuration/views/config.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/backup_configuration/views/config-zh.js
// Module:    /templates/backup_configuration/views/config-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Friday":"星期五","Monday":"星期一","Saturday":"星期六","Sunday":"星期日","The system successfully saved the backup configuration.":"The system successfully saved the backup configuration.","Thursday":"星期四","Tuesday":"星期二","Wednesday":"星期三"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
