//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/license_purchase/views/checkoutController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/license_purchase/views/checkoutController-id.js
// Module:    /templates/license_purchase/views/checkoutController-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Error: “[_1]”":"Kesalahan: “[_1]”","Redirecting to the [output,acronym,WHM,WebHost Manager] interface …":"Mengalihkan ke antarmuka [output,acronym,WHM,WebHost Manager] …","The system encountered a token validation error.":"Sistem menemui kesalahan validasi token.","The system encountered an error when it accessed the cPanel Store login [output,acronym,URL,Uniform Resource Locator]: [_1]":"The system encountered an error when it accessed the cPanel Store login [output,acronym,URL,Uniform Resource Locator]: [_1]","The system encountered an error when it generated your license order.":"Sistem menemui kesalahan saat membuat pesanan lisensi Anda.","The system encountered an error when it updated your license.":"Sistem menemui kesalahan saat memperbarui lisensi Anda.","The system encountered an error.":"Sistem menemui kesalahan.","The system successfully canceled the order.":"Sistem berhasil membatalkan pesanan.","The system successfully updated the license.":"Sistem berhasil memperbarui lisensi."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
