//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/license_purchase/views/checkoutController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/license_purchase/views/checkoutController-fil.js
// Module:    /templates/license_purchase/views/checkoutController-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Error: “[_1]”":"Error: “[_1]”","Redirecting to the [output,acronym,WHM,WebHost Manager] interface …":"Redirecting to the [output,acronym,WHM,WebHost Manager] interface …","The system encountered a token validation error.":"The system encountered a token validation error.","The system encountered an error when it accessed the cPanel Store login [output,acronym,URL,Uniform Resource Locator]: [_1]":"The system encountered an error when it accessed the cPanel Store login [output,acronym,URL,Uniform Resource Locator]: [_1]","The system encountered an error when it generated your license order.":"The system encountered an error when it generated your license order.","The system encountered an error when it updated your license.":"The system encountered an error when it updated your license.","The system encountered an error.":"The system encountered an error.","The system successfully canceled the order.":"The system successfully canceled the order.","The system successfully updated the license.":"The system successfully updated the license."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
