#!/bin/bash
# clamd - System V init script for CentOS
#
# chkconfig: 2345 13 13
# description: clamd

# Source function library.
. /etc/init.d/cpfunctions

if [ -e "/etc/clamddisable" ]; then
	exit 1
fi

NAME="clamd"
PIDFILE="/var/run/$NAME.pid"
PROG="/usr/sbin/$NAME"

start()
{
    action "Starting $NAME:" $PROG
}

stop()
{
    echo -n "Stopping Clam AntiVirus Daemon: "
	killproc $PROG
	rm -f /var/clamav/clamd.socket
	rm -f /var/run/clamav/clamav.pid
}

case "$1" in
	  start)
	    start
		;;
      stop)
        stop
        ;;
      restart)
        stop
        start
        ;;
      status)
        status $PROG
        ;;
      *)
        echo "Usage: $NAME {start|stop|restart|status}"
        ;;
esac
