#!/bin/bash
#
# cpanellogd - System V init script for CentOS
#
# chkconfig: 2345 82 82
# description: cpanellogd

# source function library
. /etc/init.d/cpfunctions

NAME="cpanellogd"
PROG="/usr/local/cpanel/$NAME"
PIDFILE="/var/run/$NAME.pid"

start()
{
    action "Starting $NAME:" $PROG
}

stop()
{
    if [ -e "$PIDFILE" ]; then
        rm $PIDFILE
    fi

    echo "Shutting down $NAME: "
    killproc "$PROG"
}

case "$1" in
  start)
        start
        ;;
  stop)
       stop
       ;;
  restart)
       stop
       start
       ;;
  status)
       status "$PROG"
       ;;
  *)
       echo "Usage: $NAME {start|stop|restart|status}"
esac

