#!/bin/bash
#
# cpdavd - System V init script for CentOS
#
# chkconfig: 2345 82 82
# description: cpdavd

# source function library
. /etc/init.d/cpfunctions

NAME="cpdavd"
LONGNAME="cpdavd - accepting connections on 2077, 2078, 2079 and 2080"
PROG="/usr/local/cpanel/libexec/$NAME"
PIDFILE="/var/run/$NAME.pid"

start()
{
    action "Starting $NAME: " $PROG --start
}

stop()
{
    action "Shutting down $NAME: " $PROG --stop
}

case "$1" in
  start)
        start
        ;;
  stop)
       stop
       ;;
  restart)
       stop
       start
       ;;
  status)
       status $NAME
       ;;
  *)
       echo "Usage: $NAME {start|stop|restart|status}"
esac

