#!/bin/bash
#
# cpsrvd - System V init script for CentOS
# config      - /var/cpanel/cpanel.config
#
# chkconfig: 2345 88 88
# description: cpsrvd

# source function library
. /etc/init.d/cpfunctions

NAME="cpsrvd"
PROG="/usr/local/cpanel/$NAME"
PIDFILE="/var/run/$NAME.pid"

start()
{
    action "Starting $NAME:" $PROG
}

stop()
{
    rm -f $PIDFILE
    echo "Shutting down $NAME: "
    killproc $PROG
}

case "$1" in
  start)
        start
        ;;
  stop)
       stop
       ;;
  restart)
       stop
       start
       ;;
  status)
       status $PROG
       ;;
  *)
       echo "Usage: $NAME {start|stop|restart|status}"
esac

