#!/bin/bash
#
# mysqld	This shell script takes care of starting and stopping
#		the MySQL subsystem (mysqld).
#
# chkconfig: 2345 40 40
# description:	MySQL database server.
# processname: mysqld
# config: /etc/my.cnf
# pidfile: /var/run/mysqld/mysqld.pid

# Source function library.
. /etc/init.d/cpfunctions

# Source networking configuration.
. /etc/sysconfig/network


prog="MySQL"

# extract value of a MySQL option from /etc/my.cnf
# Usage: get_mysql_option FILE VARNAME DEFAULT
# result is returned in $result
# Ugly as this is, it knows nothing of option file sections ...
get_mysql_option(){
	result=`sed -n "s/^[ \t]*$2[ \t]*=[ \t]*//p" "$1" 2>/dev/null | tail -n 1`
	if [ -z "$result" ]; then
	    # not found, use default
	    result="$3"
	else
	    # found, still have to deal with quoting and end-of-line comments
	    dequoted=`echo "$result" | sed "s/^'\([^']*\)'.*$/\1/"`
	    if [ x"$dequoted" != x"$result" ]; then
		result="$dequoted"
	    else
		dequoted=`echo "$result" | sed 's/^"\([^"]*\)".*$/\1/'`
		if [ x"$dequoted" != x"$result" ]; then
		    result="$dequoted"
		else
		    result=`echo "$result" | sed 's/^\([^ \t#]*\).*$/\1/'`
		fi
	    fi
	fi
}

get_mysql_option /etc/my.cnf datadir "/var/lib/mysql"
datadir="$result"
get_mysql_option /etc/my.cnf socket "$datadir/mysql.sock"
socketfile="$result"
get_mysql_option /etc/my.cnf err-log "/var/log/mysqld.log"
errlogfile="$result"
get_mysql_option /etc/my.cnf pid-file "/var/lib/mysql/$(hostname).pid"
mypidfile="$result"

start(){
	touch "$errlogfile"
	chown mysql:mysql "$errlogfile"
	chmod 0640 "$errlogfile"
	[ -x /sbin/restorecon ] && /sbin/restorecon "$errlogfile"
	if [ ! -d "$datadir/mysql" ] ; then
	    action $"Initializing MySQL database: " /usr/sbin/mysqld --initialize --user=mysql
	    ret=$?
	    chown -R mysql:mysql "$datadir"
	    if [ $ret -ne 0 ] ; then
		return $ret
	    fi
	fi
	chown -R mysql:mysql "$datadir"
	chmod 0755 "$datadir"
	# The reason for explicitly specifying --pid-file is that there may
	# be no such entry in my.cnf, and the default behavior will be to not
	# create it at all...
	/usr/bin/mysqld_safe  --defaults-file=/etc/my.cnf --pid-file="$mypidfile" >/dev/null 2>&1 &
	ret=$?
	# Spin for a maximum of N seconds waiting for the server to come up.
	# Rather than assuming we know a valid username, accept an "access
	# denied" response as meaning the server is functioning.
	if [ $ret -eq 0 ]; then
	    STARTTIMEOUT=10
	    while [ $STARTTIMEOUT -gt 0 ]; do
		RESPONSE=`/usr/bin/mysqladmin -uUNKNOWN_MYSQL_USER ping 2>&1` && break
		echo "$RESPONSE" | grep -q "Access denied for user" && break
		sleep 1
		let STARTTIMEOUT=${STARTTIMEOUT}-1
	    done
	    if [ $STARTTIMEOUT -eq 0 ]; then
                    echo "Timeout error occurred trying to start MySQL Daemon."
                    echo $"Starting $prog"
            else
                    echo $"Starting $prog"
            fi
	else
    	    echo $"Starting $prog"
	fi
	[ $ret -eq 0 ] && touch /var/lock/subsys/mysqld
	return $ret
}

stop(){
        /bin/kill `cat "$mypidfile"  2>/dev/null ` >/dev/null 2>&1
	ret=$?
	if [ $ret -eq 0 ]; then
	    sleep 2
	    rm -f /var/lock/subsys/mysqld
	    rm -f "$socketfile"
	    echo $"Stopping $prog"
	else
    	    action $"Stopping $prog"
	fi
	return $ret
}

restart(){
    stop
    sleep 1
    start
}

condrestart(){
    [ -e /var/lock/subsys/mysqld ] && restart || :
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status mysqld
    ;;
  restart)
    restart
    ;;
  condrestart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|condrestart|restart}"
    exit 1
esac

exit $?
