#!/bin/bash
#
# smtpmailgidonly - System V init script for CentOS
#
# chkconfig: 2345 55 55
# description: smtpmailgidonly

# source function library
. /etc/init.d/cpfunctions

NAME="smtpmailgidonly"
PROG="/usr/local/cpanel/scripts/smtpmailgidonly"
PIDFILE="/var/run/$NAME.pid"

start()
{
    echo "Starting $NAME: "
    daemon "$PROG" "on"
}

stop()
{
    echo "Shutting down $NAME: "
    daemon "$PROG" "off"
}

case "$1" in
  start)
        start
        ;;
  stop)
       stop
       ;;
  restart)
       stop
       start
       ;;
  status)
       ;;
  *)
       echo "Usage: $NAME {start|stop|restart|status}"
esac
