#!/bin/bash
# syslogd - System V init script for CentOS
#
# chkconfig: 2345 64 64
# description: syslogd

# Source function library.
. /etc/init.d/cpfunctions

SYSNAME='syslogd'
KSYSNAME='klogd'
SYSPROG="/sbin/$SYSNAME"
KSYSPROG="/sbin/$KSYSNAME"
SYSPIDFILE="/var/run/$SYSNAME.pid"
KSYSPIDFILE="/var/run/$KSYSNAME.pid"

# Source config
if [ -f /etc/sysconfig/syslog ] ; then
    . /etc/sysconfig/syslog
else
    SYSLOGD_OPTIONS="-m 0"
    KLOGD_OPTIONS="-2"
fi

start()
{
    echo "Starting $SYSNAME: "
    daemon "$SYSPROG" "$SYSLOGD_OPTIONS"
    echo ""
    echo "Starting $KSYSNAME: "
    daemon "$KSYSPROG" "$KLOGD_OPTIONS"
}

stop()
{
    echo "Shutting down $SYSNAME: "
    killproc $SYSPROG
    echo ""
    echo "Shutting down $KSYSNAME: "
    if [ -f "$KSYSPIDFILE" ]; then
        kill `cat $KSYSPIDFILE`
    fi
}

case "$1" in
    start)
        start
		;;
	stop)
	    stop
	    ;;
	restart)
        stop
        start
        ;;
	status)
	    status $SYSNAME
	    status $KSYSNAME
	    ;;
	*)
	    echo "Usage: $NAME {start|stop|restart|status}"
	    ;;
esac
