#!/bin/bash
#
# tailwatchd - System V init script for CentOS
#
# chkconfig: 2345 82 82
# description: tailwatchd

# source function library
. /etc/init.d/cpfunctions

NAME="tailwatchd"
LONGNAME="tailwatchd - configurable log processesing daemon"
PROG="/usr/local/cpanel/scripts/restartsrv_$NAME --no-verbose"

start()
{
    action "Starting $NAME: " $PROG
}

stop()
{
    action "Shutting down $NAME: " $PROG --stop
}

case "$1" in
  start)
        start
        ;;
  stop)
       stop
       ;;
  restart)
       stop
       start
       ;;
  status)
       $PROG --status
       ;;
  *)
       echo "Usage: $NAME {start|stop|restart|status}"
esac

