#!/bin/bash
# xinetd - System V init script for CentOS
#
# chkconfig: 2345 70 70
# description: xinetd

if [ -e '/etc/inetddisable' ]; then
	exit 1
fi

if [ -e '/etc/xinetddisable' ]; then
	exit 1
fi

# Source function library.
. /etc/init.d/cpfunctions

NAME='xinetd'
PROG="/usr/sbin/$NAME"
PIDFILE="/var/run/$NAME.pid"


start()
{
    echo "Starting $NAME: "
    daemon $PROG -pidfile "/var/run/$NAME.pid" -stayalive
}

stop()
{
    rm -f "/var/lock/subsys/$NAME"
    echo "Shutting down $NAME: "
    killproc $PROG
}

case "$1" in
	start)
	    start
		;;
	stop)
	    stop
	    ;;
	restart)
        stop
        start
        ;;
	status)
	    status $PROG
	    ;;
	*)
        echo "Usage: $NAME {start|stop|restart|status}"
        ;;
esac
