//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/zone_editor/views/manage.js
// Generated: /usr/local/cpanel/base/sharedjs/zone_editor/views/manage-id.js
// Module:    legacy_shared/zone_editor/views/manage-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Certificate Authority":"Otoritas Sertifikat","Copy failed.":"Penyalinan gagal.","Mail Address for Notifications":"Alamat Email untuk Notifikasi","Only 1 “[_1]” record may exist per name. Rename or delete [_2]’s extra “[_1]” [numerate,_3,record,records].":"Only 1 “[_1]” record may exist per name. Rename or delete [_2]’s extra “[_1]” [numerate,_3,record,records].","Successfully copied to the clipboard.":"Berhasil disalin ke papan klip.","The certificate authority’s domain name.":"Nama domain otoritas sertifikat.","The location to which the certificate authority will report exceptions. Either a [asis,mailto] or standard [asis,URL].":"Lokasi tempat pelaporan pengecualian oleh otoritas sertifikat. Dapat berupa [asis,mailto] maupun [asis,URL] standar.","You successfully deleted the [_1] record.":"Anda berhasil menghapus catatan “[_1]”.","You successfully deleted the [_1] record: [_2]":"Anda berhasil menghapus catatan “[_1]”: [_2]","You successfully reset the zone for “[_1]”.":"Anda berhasil mengatur ulang zona untuk “[_1]”.","You successfully saved [quant,_1,record,records] for “[_2]”.":"Anda berhasil menyimpan [quant,_1, catatan, catatan] untuk “[_2]”.","You successfully saved the following [_1] record for “[_2]”: “[_3]”.":"Anda berhasil menyimpan catatan [_1] untuk “[_2]”: “[_3]”.","[_1]’s “[_2]” [numerate,_3,,records have] mismatched [asis,TTL] [numerate,_3,,values] ([list_and,_4]). Records of the same name and type must always have the same [asis,TTL] value.":"[_1]’s “[_2]” [numerate,_3,,records have] mismatched [asis,TTL] [numerate,_3,,values] ([list_and,_4]). Records of the same name and type must always have the same [asis,TTL] value."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
