# /etc/bashrc

# System wide functions and aliases
# Environment stuff goes in /etc/profile

# For some unknown reason bash refuses to inherit
# PS1 in some circumstances that I can't figure out.
# Putting PS1 here ensures that it gets loaded every time.
alias which="type -path"
PS1="\u@\h [\w]# "

whoami=`whoami`
if [ -e "~/.dns" ]; then
	DNS=`cat ~/.dns`
	PS1="\u@$DNS [\w]# "
else
	if [ -e "/var/cpanel/users/$whoami" ]; then
		eval `grep DNS= /var/cpanel/users/$whoami`

		if [ ! "$DNS" = "" ]; then
			echo -n "$DNS" > ~/.dns
			PS1="\u@$DNS [\w]# "
		fi
	fi
fi

if [ ! -e ~/public_ftp ]; then
        mkdir -p ~/public_ftp
fi

mesg y

#alias monitor_logins="watch -n 1 w -hs"
#alias list_processes="ps -uxa | more"
# Now for the dos users
alias dir="ls"
alias copy="cp"
alias del="rm"
alias deltree="rm -r"
alias move="mv"
alias ff="whereis"
alias attrib="chmod"
alias edit="pico"
alias chdir="cd"
alias mem="top"
alias search="grep"
alias pico="pico -w -z"


LS_OPTIONS='--color=tty -F -a -b -T 0';
export LS_OPTIONS;
alias ls='/bin/ls $LS_OPTIONS';
alias dir='/bin/ls $LS_OPTIONS --format=vertical';
alias vdir='/bin/ls $LS_OPTIONS --format=long';
alias d=dir;
alias v=vdir;
eval `dircolors -b`


export JAVA_HOME=/usr/local/jdk
export PATH=$JAVA_HOME/bin:$PATH
export CLASSPATH=.:$JAVA_HOME/lib/classes.zip
export PATH="$PATH:/usr/local/bin:/usr/X11R6/bin"

