//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/server_profile/index.cmb.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/server_profile/index.cmb-ru.js
// Module:    /templates/server_profile/index.cmb-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Activating Profile …":"Активация профиля …","Activation Failed":"Ошибка активации","Activation Successful":"Активация завершена успешно","Disabled":"Отключено","Enabled":"Включены","Successfully changed the server profile to “[_1]”.":"Successfully changed the server profile to “[_1]”.","The profile activation log is located at: [_1]":"The profile activation log is located at: [_1]","The system failed to change the server profile to “[_1]”.":"The system failed to change the server profile to “[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
