//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/config.cmb.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/config.cmb-it.js
// Module:    /templates/mod_security/config.cmb-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Configure Global Directives":"Configura direttive globali","The system experienced an unknown error when it attempted to save the file.":"Il sistema ha riscontrato un errore sconosciuto durante il tentativo di salvataggio del file.","The value must start with the “[_1]” character.":"Il valore deve iniziare con il carattere “[_1]”.","The value that you provided is not a valid [asis,honeypot] access key. This value must be a sequence of 12 lower-case alphabetic characters.":"Il valore fornito non è una chiave di accesso [asis,honeypot] valida. Questo valore deve essere una sequenza di 12 caratteri alfanumerici minuscoli."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
