//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/index.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/index-en.js
// Module:    /templates/mod_security/index-en
// Locale:    en
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add Custom Rule":"Add Custom Rule","Copy Rule":"Copy Rule","Edit Custom Rule":"Edit Custom Rule","Edit Custom Rules":"Edit Custom Rules","Hits List":"Hits List","Report ModSecurity Hit":"Report ModSecurity Hit","Report ModSecurity Rule":"Report ModSecurity Rule","Rules List":"Rules List"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
