//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/index.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/index-ro.js
// Module:    /templates/mod_security/index-ro
// Locale:    ro
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add Custom Rule":"Adăugare regulă particularizată","Copy Rule":"Copiere regulă","Edit Custom Rule":"Editare regulă particularizată","Edit Custom Rules":"Editare reguli particularizate","Hits List":"Lista de potriviri","Report ModSecurity Hit":"Raportare potrivire ModSecurity","Report ModSecurity Rule":"Raportare regulă ModSecurity","Rules List":"Listă cu reguli"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
