//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/index.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/index-uk.js
// Module:    /templates/mod_security/index-uk
// Locale:    uk
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add Custom Rule":"Додати користувацьке правило","Copy Rule":"Копіювати правило","Edit Custom Rule":"Редагувати користувацьке правило","Edit Custom Rules":"Редагувати користувацькі правила","Hits List":"Список відвідувань","Report ModSecurity Hit":"Подати звіт про звернення ModSecurity","Report ModSecurity Rule":"Подати звіт про правило ModSecurity","Rules List":"Список правил"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
