//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/js2/contact/index.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/js2/contact/index-cs.js
// Module:    /jupiter/js2/contact/index-cs
// Locale:    cs
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Success!":"Úspěch!","The system failed to save your other contact preferences due to the following error: [_1]":"The system failed to save your other contact preferences due to the following error: [_1]","You have unset your contact email addresses.":"You have unset your contact email addresses.","You must enter your password to update your contact email addresses.":"You must enter your password to update your contact email addresses.","Your new contact email [quant,_1,address has,addresses have] been saved.":"Your new contact email [quant,_1,address has,addresses have] been saved."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
