//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/js/filemanager.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/js/filemanager-ro.js
// Module:    /jupiter/js/filemanager-ro
// Locale:    ro
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Cancel":"Revocare","Change Permissions":"Modificare permisiuni","Close":"Închidere","Compress Files":"Compress Files","Confirm":"Confirmare","Copy Files":"Copy Files","Create New File":"Create New File","Create New Folder":"Create New Folder","Delete Files":"Delete Files","Edit":"Editare","Empty Trash":"Golire Resturi","Extract Files":"Extract Files","Move Files":"Move Files","OK":"OK","Rename File":"Redenumire fişier","Restore Files":"Restore Files","Save":"Salvare"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
