//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/convert_addon_to_account/index.cmb.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/convert_addon_to_account/index.cmb-zh.js
// Module:    /templates/convert_addon_to_account/index.cmb-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Conversion Completed":"转换已完成","Conversion Failed":"转换失败","Disabled because there are no databases to move":"已禁用，因为没有数据库可供移动","Disabled because there are no email-related items to move":"已禁用，因为没有雨电子邮件有关的项可供移动","Displaying [numf,_1] to [numf,_2] out of [quant,_3,item,items]":"正在显示 [numf,_1] 至 [numf,_2] 项，共 [quant,_3,个项目,个项目]","Done":"完成","Failed":"失败","In Progress":"正在进行","Not Selected":"未选择","Selected":"选定","The conversion of the domain “[_1]” failed.":"域“[_1]”转换失败。","The conversion of the domain “[_1]” succeeded.":"域“[_1]”转换成功。","The domain does not have an [asis,SSL] certificate installed.":"域没有安装 [asis,SSL] 证书。","The domain does not have autoresponders.":"域没有自动回复器。","The domain does not have email accounts.":"域没有电子邮件帐户。","The domain does not have email forwarders.":"域没有电子邮件转发器。","The system started the conversion process for “[_1]”.":"系统已为“[_1]”启动转换进程。","You selected the following [asis,MySQL] databases to copy:":"You selected the following [asis,MySQL] databases to copy:","You selected the following [asis,MySQL] databases to move:":"You selected the following [asis,MySQL] databases to move:","[quant,_1,Autoresponder,Autoresponders]":"[quant,_1,自动回复器,自动回复器]","[quant,_1,Domain forwarder,Domain forwarders]":"[quant,_1,个域转发器,个域转发器]","[quant,_1,Email account,Email accounts]":"[quant,_1,电子邮件帐户,电子邮件帐户]","[quant,_1,Email forwarder,Email forwarders]":"[quant,_1,电子邮件转发器,电子邮件转发器]","[quant,_1,Forwarder,Forwarders]":"[quant,_1,转发器,转发器]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
