#!/usr/local/cpanel/3rdparty/bin/perl
# Homeloader - PECL extension which alters the PHP include path for user
# cpanel - /usr/local/cpanel/src/userphp/install
#
# Copyright (c) 2013, cPanel, Inc.
# All rights reserved.
# http://cpanel.net
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the owner nor the names of its contributors may be
# used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

use Cpanel::PHPINI;

chdir '/usr/local/cpanel/src/userphp' or die;

my $installed = 0;

my @prefixes = ( '/usr/local', '/usr/local/php4' );
if (@ARGV) {
    @prefixes = @ARGV;
}

foreach my $php_prefix (@prefixes) {
    next unless ( -e $php_prefix . '/lib/php.ini' && -e $php_prefix . '/bin/php' && -e $php_prefix . '/bin/phpize' && -e $php_prefix . '/bin/php-config' );
    system( $php_prefix . '/bin/phpize' );
    system( './configure', '--with-php-config=' . $php_prefix . '/bin/php-config' ) && next;
    system('make clean')                                                            && next;
    system('make')                                                                  && next;
    system( 'make', 'install' )                                                     && next;
    system( 'make', 'clean' )                                                       && next;
    my ( $ok, $res ) = Cpanel::PHPINI::install_extension( 'homeloader.so', $php_prefix );
    $installed = 1 if $ok;
    print $res . "\n";
}

if ($installed) {
    exit 0;
}
else {
    exit 1;
}
