<div>
    <hr />
    <pre>$window.location.path = {{$window.location.path}}</pre>
    <pre>$window.location.search = {{$window.location.search}}</pre>
    <pre>$location.path() = {{$location.path()}}</pre>
    <pre>$location.search() = {{$location.search()}}</pre>
    <pre>$route.current.templateUrl = {{$route.current.templateUrl}}</pre>
    <pre>$route.current.params = {{$route.current.params}}</pre>
    <pre>$route.current.scope = {{$route.current.scope}}</pre>
    <pre>$routeParams = {{$routeParams}}</pre>
</div>
