//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/apps/mailinglists/controllers/mailingListsController.js
// Generated: /usr/local/cpanel/share/apps/mailinglists/controllers/mailingListsController-sv.js
// Module:    shared/mailinglists/controllers/mailingListsController-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Access":"Åtkomst","Admin":"Admin","Functions":"Funktioner","List Name":"Listnamn","Usage":"Användning"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
