<form id="theFormBasic" name="theFormBasic">
    <cp-file-upload
        id="a-file"
        ng-model="file"
        title="Title"
        browse-button-label = "Browser"
        delete-button-title = "Delete Logo"
        confirm-delete-message = "Are you sure you want to delete this file?"
        preview-title = "Logo Preview"
        help="The file must be a .svg image."
        file-type-error="You must select a .svg image."
        mime-types="['image/svg+xml']">
    </cp-file-upload>
    <button type="submit">Submit</button>
</form>
<form id="theForm" name="theForm">
    <cp-file-upload
        id="the-file"
        ng-model="theModel.file"
        title="Title"
        browse-button-label = "Browser"
        delete-button-title = "Delete Logo"
        confirm-delete-message = "Are you sure you want to delete this file?"
        preview-title = "Logo Preview"
        help="The file must be a .svg image."
        file-type-error="You must select a .svg image."
        mime-types="['image/svg+xml']"
        on-delete="delete(theModel.file)"
        on-change="change(theModel.file)">
    </cp-file-upload>
    <button type="submit">Submit</button>
</form>
