<div class="form-group">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <label id="file_upload_{{ ::id }}_title"
                   for="file_upload_{{ ::id }}_file">
                {{ ::title }}
            </label>
        </div>
    </div>
    <div class="row">
        <div class="{{inputClasses}}">
            <div class="upload-field">
                <span class="btn-wrap">
                    <input id="file_upload_{{ ::id }}_file"
                        name="file_upload_{{ ::id }}_file"
                        type="file"
                        ng-model="model"
                        file-size
                        file-max-size
                        file-reader
                        ng-change="change()"
                        file-type="types"/>
                    <span id="file_upload_{{ ::id }}_browse_btn"
                        class="btn btn-default">
                        {{ ::browseButtonLabel }}
                    </span>
                </span>
                <span trigger-for="file_upload_{{ ::id }}_file">
                    <span id="file_upload_{{ ::id }}_file_image"
                          class="far fa-image fa-lg"
                          ng-show="model.filename"
                          aria-hidden="true">
                    </span>
                    <span id="file_upload_{{ ::id }}_filename"
                        class="filename"
                        ng-show="model.filename">
                        {{model.filename}}
                    </span>
                </span>
                <button id="file_upload_{{ ::id }}_delete"
                    type="button"
                    class="btn btn-default pull-right flip"
                    title="{{ ::deleteButtonTitle }}"
                    ng-class="{'btn-loading': deleteLoading}"
                    ng-show="model.filename"
                    ng-click="confirmDelete(model)"
                    ng-disabled="deleteLoading">
                    <span class="btn-label">
                        <span class="glyphicon glyphicon-trash"></span>
                    </span>
                    <span class="glyphicon glyphicon-refresh btn-loading-indicator"></span>
                </button>
                <span class="help-block">
                    {{ ::help }}
                </span>
            </div>
        </div>
        <div class="{{previewClasses}}">
            <div ng-show="!!model.data"
                 class="preview-background"
                 style="background-color: {{ previewBgColor || 'inherit' }}">
                <img id="file_upload_{{ ::id }}_preview"
                        src="{{model.data}}"
                        ng-show="model.data"
                        alt="{{ ::previewTitle }}" />
            </div>
        </div>
        <div id="file_upload_{{::id}}_errors"
            class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <ul class="validation-container"
                ng-show="isInvalid(id + '_file')">
                <li class="validation validation-error"
                    ng-show="errors(id + '_file', 'filetype')">
                    <span class="glyphicon glyphicon-exclamation-sign"></span>
                    <span class="validation-message">
                        {{ ::fileTypeError }}
                    </span>
                </li>
                <li class="validation validation-error"
                    ng-show="errors(id + '_file', 'fileSize')">
                    <span class="glyphicon glyphicon-exclamation-sign"></span>
                    <span class="validation-message">
                        {{ ::fileEmptyError }}
                    </span>
                </li>
                <li class="validation validation-error"
                    ng-show="errors(id + '_file', 'fileMaxSize')">
                    <span class="glyphicon glyphicon-exclamation-sign"></span>
                    <span class="validation-message">
                        {{ ::fileMaxSizeError }}
                    </span>
                </li>
            </ul>
        </div>
    </div>
</div>