<form id="test-valid">
    <input type="file" id="the-file" name="theFile" ng-model="model" file-reader ng-change="changed(model)" />
</form>
<form id="test-missing-model">
    <input type="file" name="theFile" id="the-file" file-reader />
</form>
<form id="test-invalid-type">
    <input type="text" name="theFile" id="the-file" ng-model="model" file-reader />
</form>
<form id="test-invalid-control">
    <div type="text" name="theFile" type="file" id="the-file" ng-model="model" file-reader></div>
</form>
<form id="test-invalid-no-type">
    <input id="the-file" name="theFile" ng-model="model" file-reader />
</form>
<form id="test-invalid-max-size">
    <input id="the-file" name="theFile" type="file"  ng-model="model" file-reader file-max-size="1" />
</form>
<form id="test-invalid-min-size">
    <input id="the-file" name="theFile" type="file" ng-model="model" file-reader file-size />
</form>
<form id="test-invalid-absolute-size">
    <input id="the-file" name="theFile" type="file"  ng-model="model" file-reader />
</form>
<form id="test-no-files">
    <input id="the-file" name="theFile" type="file"  ng-model="model" file-reader />
</form>
