<div class="modal-header">
    <h3 class="modal-title">{{ LOCALE.maketext('Confirm Delete') }}</h3>
</div>
<div class="modal-body">
    <p>
        <span id="dialog_text_info">
            {{ ::message }}
        </span>
    </p>
    <span id="dialog_text_confirm">
        {{ LOCALE.maketext('Are you sure you want to continue?') }}
    </span>
</div>
<div class="modal-footer">
    <button id="dialog_btn_delete"
        class="btn btn-primary"
        ng-click="close(true)">
        {{ LOCALE.maketext('Delete') }}
    </button>
    <button id="dialog_btn_cancel"
        class="btn btn-default"
        ng-click="close(false)">
        {{ LOCALE.maketext('Cancel') }}
    </button>
</div>