//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/feature/views/featureListController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/feature/views/featureListController-zh.js
// Module:    /templates/feature/views/featureListController-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"There was a problem loading the page. The system is reporting the following error: [_1].":"加载页面时出现问题。 系统正在报告以下错误: [_1]。","You successfully deleted the “[_1]” feature list.":"您已成功删除“[_1]”功能列表。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
