//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/email_accounts/views/list.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/email_accounts/views/list-ja.js
// Module:    /jupiter/email_accounts/views/list-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” deleted.":"アカウント「[_1]」が削除されました。","Delete ([numf,_1])":"Delete ([numf,_1])","Delete the selected [quant,_1,email account,email accounts]?":"Delete the selected [quant,_1,email account,email accounts]?","Delete “[_1]”?":"「[_1]」を削除しますか？","Deleted [numf,_1] email accounts.":"Deleted [numf,_1] email accounts.","Email account “[_1]” deleted.":"メールアカウント「[_1]」が削除されました。","[_1] - [_2] of [_3]":"[_3]の[_1] - [_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
