#!/usr/local/cpanel/3rdparty/bin/perl

my $installed = 0;
open( RUBY, '<', '/usr/bin/ruby' );
while (<RUBY>) {
    if (/cPanel Ruby Wrapper ([\d\.]+)/) {
        $ver       = $1;
        $installed = 1;
        last();
    }
}
close(RUBY);
print "$installed";
