//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/libraries/cjt2/src/util/httpStatus.js
// Generated: /usr/local/cpanel/share/libraries/cjt2/src/util/httpStatus-pl.js
// Module:    cjt/util/httpStatus-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Accepted":"Zaakceptowane","Bad Gateway":"Nieprawidłowa brama","Bad Request":"Nieprawidłowe żądanie","Conflict":"Konflikt","Continue":"Kontynuuj","Created":"Utworzono","Expectation Failed":"Błąd oczekiwania","Forbidden":"Zabronione","Found":"Znalezione","Gateway Timeout":"Limit czasu bramy","Gone":"Minęło","HTTP Version Not Supported":"Nieobsługiwana wersja protokołu HTTP","Internal Server Error":"Wewnętrzny błąd serwera","Length Required":"Wymagana długość","Method Not Allowed":"Niedozwolona metoda","Moved Permanently":"Trwale przeniesione","Multiple Choices":"Możliwość wielokrotnego wyboru","No Content":"Brak treści","Non-Authoritative Information":"Nieautorytatywne informacje","Not Acceptable":"Nieakceptowalne","Not Found":"Nie znaleziono","Not Implemented":"Niezaimplementowane","Not Modified":"Niezmodyfikowane","OK":"OK","Partial Content":"Zawartość częściowa","Payment Required":"Wymagana płatność","Precondition Failed":"Błąd warunku wstępnego","Proxy Authentication Required":"Wymagane uwierzytelnianie serwera proxy","Request Entity Too Large":"Zbyt duży obiekt żądania","Request Timeout":"Limit czasu żądania","Request-URI Too Long":"Zbyt długi identyfikator URI żądania","Requested Range Not Satisfiable":"Niewłaściwy żądany zakres","Reset Content":"Resetuj treść","See Other":"Zobacz inne","Service Unavailable":"Usługa niedostępna","Switching Protocols":"Przełączanie protokołów","Temporary Redirect":"Tymczasowe przekierowanie","Unauthorized":"Brak autoryzacji","Unknown Error":"Nieznany błąd","Unsupported Media Type":"Nieobsługiwany typ multimediów","Use Proxy":"Użyj serwera proxy"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
