//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/libraries/cjt2/src/util/httpStatus.js
// Generated: /usr/local/cpanel/share/libraries/cjt2/src/util/httpStatus-vi.js
// Module:    cjt/util/httpStatus-vi
// Locale:    vi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Accepted":"Đã chấp nhận","Bad Gateway":"Lỗi Cổng Nối","Bad Request":"Lỗi Yêu Cầu","Conflict":"Xung đột","Continue":"Tiếp Tục","Created":"Đã tạo","Expectation Failed":"Lỗi chờ đợi","Forbidden":"Bị cấm","Found":"Tìm Thấy","Gateway Timeout":"Hết Thời Gian Chờ Cổng Nối","Gone":"Không hiển thị nữa","HTTP Version Not Supported":"Không Hỗ Trợ Phiên Bản HTTP","Internal Server Error":"Lỗi Máy Chủ Nội Bộ","Length Required":"Chiều Dài Bắt Buộc","Method Not Allowed":"Phương Pháp Cấm","Moved Permanently":"Di Chuyển Vĩnh Viễn","Multiple Choices":"Nhiều Lựa Chọn","No Content":"Không Có Nội Dung","Non-Authoritative Information":"Thông Tin Không Có Thẩm Quyền","Not Acceptable":"Không Chấp Nhận","Not Found":"Không Tìm Thấy","Not Implemented":"Không Thực Thi","Not Modified":"Không Được Sửa Đổi","OK":"OK","Partial Content":"Một Phần Nội Dung","Payment Required":"Cần Thanh Toán","Precondition Failed":"Lỗi Điều Kiện Tiền Đề","Proxy Authentication Required":"Cần Xác Thực Proxy","Request Entity Too Large":"Đối Tượng Yêu Cầu Quá Lớn","Request Timeout":"Hết Thời Gian Chờ Yêu Cầu","Request-URI Too Long":"URI Yêu Cầu Quá Dài","Requested Range Not Satisfiable":"Khoảng Yêu Cầu Ngoài Vùng Đáp Ứng","Reset Content":"Đặt Lại Nội Dung","See Other":"Xem Thông Tin Khác","Service Unavailable":"Không Có Dịch Vụ","Switching Protocols":"Chuyển Đổi Giao Thức","Temporary Redirect":"Chuyển Hướng Tạm Thời","Unauthorized":"Không Được Phép","Unknown Error":"Lỗi Lạ","Unsupported Media Type":"Kiểu Phương Tiện Không Được Hỗ Trợ","Use Proxy":"Dùng Proxy"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
