//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/file_and_directory_restoration/views/list.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/file_and_directory_restoration/views/list-pt_br.js
// Module:    /jupiter/file_and_directory_restoration/views/list-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Enter the exact path to the file or directory that you wish to restore.":"Digite o caminho exato para o arquivo ou diretório que deseja restaurar.","The system successfully restored the “[_1]” backup file from the date “[_2]”.":"O sistema restaurou com sucesso o arquivo de backup “[_1]” da data “[_2]”.","When you restore a backup, the system will overwrite existing files and restore deleted files.":"Quando você restaura um backup, o sistema substitui os arquivos existentes e restaura os arquivos excluídos."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
