//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/api_shell.js
// Generated: /usr/local/cpanel/base/sharedjs/api_shell-en.js
// Module:    legacy_shared/api_shell-en
// Locale:    en
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Hide Sort/Filter/Paginate Options":"Hide Sort/Filter/Paginate Options","Invalid JSON.":"Invalid JSON.","Raw view":"Raw view","Retrieving API call results …":"Retrieving API call results …","Show Sort/Filter/Paginate Options":"Show Sort/Filter/Paginate Options","Table View is unavailable for this function’s data.":"Table View is unavailable for this function’s data.","Table view":"Table view","Tree view":"Tree view","[format_bytes,_1] compressed, [format_bytes,_2] uncompressed":"[format_bytes,_1] compressed, [format_bytes,_2] uncompressed","[quant,_1,record,records], [quant,_2,field,fields] per record":"[quant,_1,record,records], [quant,_2,field,fields] per record","compressed size unknown, [format_bytes,_1] uncompressed":"compressed size unknown, [format_bytes,_1] uncompressed"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
