//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/api_shell.js
// Generated: /usr/local/cpanel/base/sharedjs/api_shell-cs.js
// Module:    legacy_shared/api_shell-cs
// Locale:    cs
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Hide Sort/Filter/Paginate Options":"Skrýt možnosti řazení, filtrování a stránkování","Invalid JSON.":"Neplatný formát JSON.","Raw view":"Nativní zobrazení","Retrieving API call results …":"Načítání výsledků volání rozhraní API…","Show Sort/Filter/Paginate Options":"Zobrazit možnosti řazení, filtrování a stránkování","Table View is unavailable for this function’s data.":"Zobrazení tabulky není pro data této funkce k dispozici.","Table view":"Tabulkové zobrazení","Tree view":"Stromové zobrazení","[format_bytes,_1] compressed, [format_bytes,_2] uncompressed":"[format_bytes,_1] komprimováno, [format_bytes,_2] nekomprimováno","[quant,_1,record,records], [quant,_2,field,fields] per record":"[quant,_1,record,records], [quant,_2,field,fields] per record","compressed size unknown, [format_bytes,_1] uncompressed":"komprimovaná velikost neznámá, [format_bytes,_1] nekomprimováno"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
