//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/email_ui_control.js
// Generated: /usr/local/cpanel/base/sharedjs/email_ui_control-es_es.js
// Module:    legacy_shared/email_ui_control-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"An unknown error occurred.":"Se produjo un error desconocido.","Checkboxes":"Casillas","Hide":"Ocultar","Jump to page.":"Vaya a la página.","Next Page":"Página siguiente","Page [numf,_1]":"Page [numf,_1]","Page [numf,_1] of [numf,_2]":"Page [numf,_1] of [numf,_2]","Previous Page":"Página anterior","Reconfigure Search":"Volver a configurar la búsqueda","Reset to Default":"Restablecer valores predeterminados","Rows per Page":"Filas por página","Select All":"Seleccionar todo","Show [quant,_1,Result,Results]":"Mostrar [quant,_1,resultado,resultados]","The search matches [quant,_1,record,records].":"La búsqueda coincide con [quant,_1,registro,registros].","You must show at least one message type.":"Muestre al menos un tipo de mensaje."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
