//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/emailstats_summary.js
// Generated: /usr/local/cpanel/base/sharedjs/emailstats_summary-el.js
// Module:    legacy_shared/emailstats_summary-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Click a row to show a detailed report.":"Κάντε κλικ σε μια γραμμή για να εμφανιστεί μια λεπτομερής αναφορά.","Data Sent":"Απεσταλμένα δεδομένα","Defer+Fail Per Hour":"Αναβολή+Αποτυχία ανά ώρα","Deferrals":"Αναβολές","Domain":"Τομέας","Failed and Deferred":"Αποτυχία και αναβολή","Failures":"Αστοχίες","Relay per Hour":"Αναμετάδοση ανά ώρα","Successful":"Επιτυχημένη","Total Messages":"Σύνολο μηνυμάτων","User":"Χρήστης"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
