//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/email_ui_control.js
// Generated: /usr/local/cpanel/base/sharedjs/email_ui_control-he.js
// Module:    legacy_shared/email_ui_control-he
// Locale:    he
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"An unknown error occurred.":"אירעה שגיאה לא ידועה.","Checkboxes":"תיבות סימון","Hide":"הסתר","Jump to page.":"דלג לדף.","Next Page":"הדף הבא","Page [numf,_1]":"דף [numf,_1]","Page [numf,_1] of [numf,_2]":"דף [numf,_1] מתוך [numf,_2]","Previous Page":"הדף הקודם","Reconfigure Search":"הגדר חיפוש מחדש","Reset to Default":"איפוס לברירת המחדל","Rows per Page":"שורות לדף","Select All":"בחר הכול","Show [quant,_1,Result,Results]":"הצג [quant,_1,תוצאה ,תוצאות]","The search matches [quant,_1,record,records].":"החיפוש מצא [quant,_1,רשומה ,רשומות].","You must show at least one message type.":"עליך להציג לפחות סוג הודעה אחד."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
