//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/emailstats_summary.js
// Generated: /usr/local/cpanel/base/sharedjs/emailstats_summary-it.js
// Module:    legacy_shared/emailstats_summary-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Click a row to show a detailed report.":"Fare clic su una riga per mostrare un rapporto dettagliato.","Data Sent":"Dati inviati","Defer+Fail Per Hour":"Differiti+Non riusciti all’ora","Deferrals":"Differimenti","Domain":"Dominio","Failed and Deferred":"Non riuscito e differito","Failures":"Errori","Relay per Hour":"Trasferimento all’ora","Successful":"Operazione completata","Total Messages":"Messaggi totali","User":"Utente"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
