//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/emailstats_summary.js
// Generated: /usr/local/cpanel/base/sharedjs/emailstats_summary-fr.js
// Module:    legacy_shared/emailstats_summary-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Click a row to show a detailed report.":"Cliquez sur une ligne pour afficher un rapport détaillé.","Data Sent":"Données envoyées","Defer+Fail Per Hour":"Reports+échecs par heure","Deferrals":"Reports","Domain":"Domaine","Failed and Deferred":"En échec et reporté","Failures":"Erreurs","Relay per Hour":"Relais par heure","Successful":"Réussite","Total Messages":"Total des messages","User":"Utilisateur"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
