//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/email_ui_control.js
// Generated: /usr/local/cpanel/base/sharedjs/email_ui_control-vi.js
// Module:    legacy_shared/email_ui_control-vi
// Locale:    vi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"An unknown error occurred.":"Xảy ra lỗi lạ.","Checkboxes":"Hộp Kiểm","Hide":"Ẩn","Jump to page.":"Chuyển đến trang.","Next Page":"Trang Tiếp Theo","Page [numf,_1]":"Trang [numf,_1]","Page [numf,_1] of [numf,_2]":"Trang [numf,_1] / [numf,_2]","Previous Page":"Trang Trước","Reconfigure Search":"Lập Lại Cấu Hình Tìm Kiếm","Reset to Default":"Đặt Lại Về Mặc Định","Rows per Page":"Số Hàng Trên Một Trang","Select All":"Chọn Tất Cả","Show [quant,_1,Result,Results]":"Hiển Thị [quant,_1,Kết Quả,Kết Quả]","The search matches [quant,_1,record,records].":"Tìm kiếm đối sánh với [quant,_1,bản ghi,bản ghi].","You must show at least one message type.":"Bạn phải hiển thị ít nhất một loại thư."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
