//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/fetch_mail_queue.js
// Generated: /usr/local/cpanel/base/sharedjs/fetch_mail_queue-he.js
// Module:    legacy_shared/fetch_mail_queue-he
// Locale:    he
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"פעולות","Are you sure you wish to attempt to deliver the entire mail queue?":"האם אתה בטוח שברצונך לנסות לשלוח את תור הדואר כולו?","Are you sure you wish to purge the entire mail queue?":"האם אתה בטוח שברצונך לנקות את תור הדואר כולו לצמיתות?","Frozen":"קפוא","Invalid Date":"תאריך לא חוקי","Message ID":"מזהה הודעה","Queued":"בתור","Recipient(s)":"נמענים","Sender":"שולח","Size":"גודל","Status":"מצב","System":"מערכת","The fetch returned no data.":"ההבאה לא החזירה נתונים.","Time Received":"שעת קבלה","You must first select at least one message in the queue.":"תחילה, עליך לבחור לפחות הודעה אחת בתור."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
