//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/ssltable.js
// Generated: /usr/local/cpanel/base/sharedjs/ssltable-es_es.js
// Module:    legacy_shared/ssltable-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Certificate ID:":"ID del certificado:","Contact your Certificate Authority ([_1]) to request a certificate renewal.":"Contacte con su autoridad de certificación ([_1]) para solicitar una renovación del certificado.","Contact your certificate authority ([_1]) to reissue this certificate with a [numf,_2]-bit key.":"Contact your certificate authority ([_1]) to reissue this certificate with a [numf,_2]-bit key.","Purchase a replacement certificate in the “[_1]”.":"Compre un certificado de reemplazo en “[_1]”.","SSL/TLS Wizard":"Asistente SSL/TLS","This certificate has expired.":"Este certificado ha expirado.","This certificate will expire in [quant,_1,day,days].":"Este certificado expirará en [quant,_1,día,días].","This certificate will expire later today.":"Este certificado expirará hoy.","This certificate’s key is too short ([quant,_1,bit,bits]). This key will not protect against a spoofing attack.":"La clave de este certificado es demasiado corta ([quant,_1,bit,bits]). Es por este motivo que no le protegerá frente a ataques de spoofing.","You should generate another self-signed certificate for [quant,_1,this domain,these domains] with a [numf,_2]-bit key.":"You should generate another self-signed certificate for [quant,_1,this domain,these domains] with a [numf,_2]-bit key.","unknown":"desconocido"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
