//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/sslwidgets.js
// Generated: /usr/local/cpanel/base/sharedjs/sslwidgets-ko.js
// Module:    legacy_shared/sslwidgets-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Certificate Expiration":"인증서 만료","Certificate Key Sizes":"인증서 키 크기","Contact your certificate authority ([_1]) to reissue this certificate with a [numf,_2]-bit key.":"인증 기관([_1])에 문의하여 이 인증서를 [numf,_2]비트 키로 재발급 받으십시오.","Contact your certificate authority to reissue this certificate with a longer key.":"더 긴 키로 이 인증서를 다시 발행하려면 인증 기관에 문의하십시오.","Generate and install a new self-signed certificate immediately. Then, replace this certificate with a certificate signed by a valid certificate authority as soon as possible.":"즉시 자체 서명 인증서를 새로 생성하여 설치하십시오. 그런 다음 이 인증서를 유효 인증 기관이 서명한 인증서로 신속히 교체하십시오.","It is highly recommended that you do not install this certificate.":"이 인증서는 설치하지 않는 것이 좋습니다.","Purchase a new certificate.":"Purchase a new certificate.","Self-Signed Certificates":"자체 서명 인증서","The recommended key size for a certificate is currently [quant,_1,bit,bits].":"인증서의 권장 키 크기는 현재 [quant,_1,비트,비트]입니다.","This certificate will expire in [quant,_1,day,days].":"이 인증서는 [quant,_1,일,일] 후 만료됩니다.","This certificate’s key is too short ([quant,_1,bit,bits]). This key will not protect against a spoofing attack.":"이 인증서의 키는 너무 짧습니다([quant,_1,비트,비트]). 이 키는 스푸핑 공격을 막아내지 못합니다.","You should generate another self-signed certificate for [quant,_1,this domain,these domains] with a [numf,_2]-bit key.":"[quant,_1,이 도메인,이들 도메인]에 [numf,_2]비트 키의 다른 자체 서명 인증서를 생성해야 합니다.","You should request a replacement certificate from the issuer ([_1]) as soon as possible.":"최대한 빠른 시간 내에 발급 기관([_1])에게 교환 인증서를 요청해야 합니다."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
