//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/sharedjs/sslwidgets.js
// Generated: /usr/local/cpanel/base/sharedjs/sslwidgets-vi.js
// Module:    legacy_shared/sslwidgets-vi
// Locale:    vi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Certificate Expiration":"Kỳ Hạn Chứng Chỉ","Certificate Key Sizes":"Kích Thước Khóa Chứng Chỉ","Contact your certificate authority ([_1]) to reissue this certificate with a [numf,_2]-bit key.":"Liên hệ tổ chức cấp chứng chỉ ([_1]) để phát hành lại chứng chỉ này với khóa [numf,_2] bit.","Contact your certificate authority to reissue this certificate with a longer key.":"Liên hệ tổ chức cấp chứng chỉ để phát hành lại chứng chỉ này với khóa dài hơn.","Generate and install a new self-signed certificate immediately. Then, replace this certificate with a certificate signed by a valid certificate authority as soon as possible.":"Tạo và cài đặt chứng chỉ tự ký mới ngay lập tức. Sau đó, thay thế chứng chỉ này bằng chứng chỉ có chữ ký của tổ chức cấp chứng chỉ hợp lệ ngay khi có thể.","It is highly recommended that you do not install this certificate.":"Bạn thực sự không nên cài đặt chứng thực này.","Purchase a new certificate.":"Purchase a new certificate.","Self-Signed Certificates":"Chứng Chỉ Tự Ký","The recommended key size for a certificate is currently [quant,_1,bit,bits].":"Kích thước khóa khuyến cáo cho chứng chỉ hiện là [quant,_1,bit,bit].","This certificate will expire in [quant,_1,day,days].":"Chứng chỉ này sẽ hết hạn trong [quant,_1,ngày,ngày].","This certificate’s key is too short ([quant,_1,bit,bits]). This key will not protect against a spoofing attack.":"Khóa của chứng chỉ này quá ngắn ([quant,_1,bit,bit]). Khóa này sẽ không bảo vệ chống lại tấn công giả mạo.","You should generate another self-signed certificate for [quant,_1,this domain,these domains] with a [numf,_2]-bit key.":"Chúng tôi khuyến cáo tạo một chứng chỉ tự ký khác cho [quant,_1,miền này,miền này] với khóa [numf,_2] bit.","You should request a replacement certificate from the issuer ([_1]) as soon as possible.":"Bạn phải yêu cầu chứng chỉ thay thế từ nhà phát hành ([_1]) càng sớm càng tốt."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
