<span data-title="{{ :: header.label }}" id="{{ :: parentID }}" class="record-status-directive">
    <span ng-if="recordLoading">
        <i class="fas fa-spinner fa-spin" aria-hidden="true"></i>
        <span class="hidden-xs" ng-bind="getLoadingMessage()"></span>
    </span>
    <span ng-if="!recordLoading" id="recordStatus_{{parentID}}" class="record-status" title="{{ statusDescription }}" ng-click="statusClicked()">
        <i class="fas" ng-class="statusIconClass" aria-hidden="true"></i>
        <span class="hidden-xs" ng-bind="statusLabel"></span>
    </span>
</span>
