//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/addRuleController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/addRuleController-fil.js
// Module:    /templates/mod_security/views/addRuleController-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"There is a duplicate [asis,ModSecurity™] rule in the staged configuration file. You cannot add a duplicate rule.":"May duplicate na rule ng [asis,ModSecurity™] rule sa staged na configuration file. Hindi ka maaaring mag-duplicate ng rule.","You have successfully saved your [asis,ModSecurity™] rule with the following ID: [_1].":"Matagumpay mong na-save ang iyong [asis,ModSecurity™] rule na may sumusunod na ID: [_1].","You successfully disabled the [asis,ModSecurity™] rule with the following ID: [_1]":"Matagumpay mong na-disable ang [asis,ModSecurity™] rule na may sumusunod na ID: [_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
