//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/addRuleController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/addRuleController-fi.js
// Module:    /templates/mod_security/views/addRuleController-fi
// Locale:    fi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"There is a duplicate [asis,ModSecurity™] rule in the staged configuration file. You cannot add a duplicate rule.":"Vaiheistetussa määritystiedostossa on [asis,ModSecurity™]-säännön kaksoiskappale. Säännön kaksoiskappaletta ei voi lisätä.","You have successfully saved your [asis,ModSecurity™] rule with the following ID: [_1].":"Olet nyt tallentanut [asis,ModSecurity™]-säännön ja seuraavan tunnuksen: [_1].","You successfully disabled the [asis,ModSecurity™] rule with the following ID: [_1]":"Olet poistanut käytöstä [asis,ModSecurity™]-säännön, jonka tunnus on seuraava: [_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
