//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/configController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/configController-tr.js
// Module:    /templates/mod_security/views/configController-tr
// Locale:    tr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system experienced an unknown error when it attempted to save the file.":"Sistem, dosyayı kaydetmeye çalışırken bilinmeyen bir hata yaşadı.","The value must start with the “[_1]” character.":"Değer “[_1]” karakteriyle başlamalıdır.","The value that you provided is not a valid [asis,honeypot] access key. This value must be a sequence of 12 lower-case alphabetic characters.":"Sağladığınız değer, geçerli bir [asis,honeypot] erişim anahtarı değil. Bu değer, 12 küçük alfabe karakterlik bir dizi olmalıdır."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
