//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/editRuleController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/editRuleController-zh_tw.js
// Module:    /templates/mod_security/views/editRuleController-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A vendor configuration file provides this rule. You cannot edit vendor rules. You can enable or disable this rule with the controls below.":"廠商組態檔提供此規則。 您無法編輯廠商規則。 您可以用下面的控制項啟用或停用此規則。","The configuration file that provides the rule “[_1]” is disabled. Whether enabled or disabled, the rule will have no visible effect until you enable the configuration file for the “[_2]” vendor.":"已停用提供規則 “[_1]” 的組態檔。 不論規則為啟用或停用狀態，都必須等到啟用 “[_2]” 廠商的組態檔後才會有可見的效果。","The rule with ID number “[_1]” is not unique. There are multiple rules that use the same ID number within the “[_2]” vendor rule set.":"識別碼為“[_1]”的規則不是唯一的。 有多個規則使用 “[_2]” 廠商規則集裡的同一個識別碼。","The rule with ID number “[_1]” is not unique. There are multiple rules that use the same ID number within your user-defined rule set.":"識別碼為 “[_1]” 的規則不是唯一的。 有多個規則使用您的使用者定義規則集裡的同一個識別碼。","The system could not find the ID number for this rule.":"系統找不到此規則的識別碼。","The system could not find the rule with ID number “[_1]” from the “[_2]” vendor rule set.":"系統在 “[_2]” 廠商規則集中找不到識別碼為 “[_1]” 的規則。","The system could not find the rule with ID number “[_1]” from your user-defined rule set.":"系統在您的使用者定義規則集中找不到識別碼為 “[_1]” 的規則。","The vendor that provides the rule “[_1]” is disabled. Whether enabled or disabled, the rule will have no visible effect until you enable that vendor.":"已停用提供規則 “[_1]” 的廠商。 不論規則為啟用或停用狀態，都必須等到啟用該廠商後才會有可見的效果。","There is a duplicate [asis,ModSecurity™] rule in the staged configuration file. You cannot add a duplicate rule.":"策畫組態檔中有重複的 [asis,ModSecurity™] 規則。 您無法新增重複的規則。","You have successfully updated the [asis,ModSecurity™] rule.":"您已成功更新 [asis,ModSecurity™] 規則。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
