//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/enableDisableConfigController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/enableDisableConfigController-es.js
// Module:    /templates/mod_security/views/enableDisableConfigController-es
// Locale:    es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system could not disable the configuration files.":"El sistema no pudo deshabilitar los archivos de configuración.","The system could not enable the configuration files.":"El sistema no pudo habilitar los archivos de configuración.","The system failed to pass the ID query string parameter.":"El sistema no pudo pasar el parámetro de la cadena de caracteres de consultas del identificador.","You have successfully disabled all of the configuration files.":"Deshabilitó todos los archivos de configuración correctamente.","You have successfully disabled some of the configuration files. The files that the system failed to disable are marked below.":"Deshabilitó algunos archivos de configuración correctamente. Los archivos que el sistema no pudo deshabilitar están marcadas a continuación.","You have successfully disabled the configuration file: [_1]":"Usted ha deshabilitado el archivo de configuración correctamente: [_1]","You have successfully enabled all of the configuration files.":"Habilitó todos los archivos de configuración correctamente.","You have successfully enabled some of the configuration files. The files that the system failed to enable are marked below.":"Habilitó algunos archivos de configuración correctamente. Los archivos que el sistema no pudo habilitar están marcadas a continuación.","You have successfully enabled the configuration file: [_1]":"Habilitó el archivo de configuración correctamente: [_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
