//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/enableDisableConfigController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/enableDisableConfigController-ja.js
// Module:    /templates/mod_security/views/enableDisableConfigController-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system could not disable the configuration files.":"システムが設定ファイルを無効化できませんでした。","The system could not enable the configuration files.":"システムが設定ファイルを有効化できませんでした。","The system failed to pass the ID query string parameter.":"システムは、IDクエリ文字列パラメータの受け渡しに失敗しました。","You have successfully disabled all of the configuration files.":"全設定ファイルの無効化に成功しました。","You have successfully disabled some of the configuration files. The files that the system failed to disable are marked below.":"一部の設定ファイルの無効化に成功しました。無効化に失敗したファイルは以下で特定されています。","You have successfully disabled the configuration file: [_1]":"設定ファイル：[_1]の無効化に成功しました。","You have successfully enabled all of the configuration files.":"全設定ファイルの有効化に成功しました。","You have successfully enabled some of the configuration files. The files that the system failed to enable are marked below.":"一部の設定ファイルの有効化に成功しました。失敗したファイルは以下で特定されています。","You have successfully enabled the configuration file: [_1]":"設定ファイル：[_1]の有効化に成功しました。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
