//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/massEditRuleController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/massEditRuleController-ja.js
// Module:    /templates/mod_security/views/massEditRuleController-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"You have successfully saved and deployed your [asis,ModSecurity™] rules.":"[asis,ModSecurity™]ルールの保存・配置に成功しました。","You have successfully saved your [asis,ModSecurity™] rules.":"[asis,ModSecurity™]ルールの保存に成功しました。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
