//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/rulesListController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/rulesListController-it.js
// Module:    /templates/mod_security/views/rulesListController-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Custom":"Personalizzato","Loading …":"Caricamento in corso…","The displayed rules are from the following vendor rule [numerate,_1,set,sets]: [list_and,_2]":"Le regole visualizzate provengono dal seguente/dai seguenti [numerate,_1,gruppo,gruppi] di regole fornitore: [list_and,_2]","There was a problem loading the page. The system is reporting the following error: [_1].":"Si è verificato un problema durante il caricamento della pagina. Segnalazione del seguente errore: [_1].","You have not selected any vendor rule sets.":"Non sono stati selezionati gruppi di regole fornitore.","You successfully deleted “[_1]” from the list of [asis,ModSecurity™] rules.":"Eliminazione di “[_1]” dall’elenco di regole [asis,ModSecurity™] completata.","You successfully deployed the staged changes and [asis,Apache] received a graceful restart request.":"Distribuzione delle modifiche in fasi completata e richiesta di riavvio regolare ricevuta da [asis,Apache].","You successfully disabled “[_1]” in the list of [asis,ModSecurity™] rules.":"Disattivazione di “[_1]” nell’elenco di regole [asis,ModSecurity™] completata.","You successfully discarded the staged changes.":"Rimozione modifiche in fasi completata.","You successfully enabled “[_1]” in the list of [asis,ModSecurity™] rules.":"Attivazione di “[_1]” nell’elenco di regole [asis,ModSecurity™] completata.","Your user-defined rules are included below.":"Le regole definite dall’utente sono incluse tra quelle elencate di seguito.","Your user-defined rules are not included below.":"Le regole definite dall’utente non sono incluse tra quelle riportate di seguito.","[quant,_1,Vendor,Vendors]":"[quant,_1,Fornitore,Fornitori]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
