//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/rulesListController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/rulesListController-pl.js
// Module:    /templates/mod_security/views/rulesListController-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Custom":"Niestandardowe","Loading …":"Ładowanie…","The displayed rules are from the following vendor rule [numerate,_1,set,sets]: [list_and,_2]":"Wyświetlone reguły pochodzą z następującego(-ych) [numerate,_1,zbioru,zbiorów] reguł dostawcy: [list_and,_2]","There was a problem loading the page. The system is reporting the following error: [_1].":"Wystąpił problem podczas ładowania strony. System zgłasza następujący błąd: [_1].","You have not selected any vendor rule sets.":"Nie wybrano żadnych zbiorów reguł dostawcy.","You successfully deleted “[_1]” from the list of [asis,ModSecurity™] rules.":"Pomyślnie usunięto regułę „[_1]” z listy reguł [asis,ModSecurity™].","You successfully deployed the staged changes and [asis,Apache] received a graceful restart request.":"Pomyślnie wdrożono etapowe zmiany i serwer [asis,Apache] odebrał bezpieczne żądanie ponownego uruchomienia.","You successfully disabled “[_1]” in the list of [asis,ModSecurity™] rules.":"Pomyślnie wyłączono regułę „[_1]” na liście reguł [asis,ModSecurity™].","You successfully discarded the staged changes.":"Pomyślnie odrzucono etapowe zmiany.","You successfully enabled “[_1]” in the list of [asis,ModSecurity™] rules.":"Pomyślnie włączono regułę „[_1]” na liście reguł [asis,ModSecurity™].","Your user-defined rules are included below.":"Twoje reguły wyznaczone przez użytkownika są uwzględnione poniżej.","Your user-defined rules are not included below.":"Twoje reguły wyznaczone przez użytkownika nie są uwzględnione poniżej.","[quant,_1,Vendor,Vendors]":"[quant,_1,dostawca,dostawców]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
