//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/vendorListController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/views/vendorListController-nb.js
// Module:    /templates/mod_security/views/vendorListController-nb
// Locale:    nb
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system experienced the following error when it attempted to install the “[_1]” vendor: [_2]":"Systemet registrerte følgende feil under forsøk på å installere leverandøren “[_1]“: [_2]","The system experienced the following error when it attempted to remove the vendor [_1]: [_2]":"Systemet registrerte følgende feil under forsøk på å fjerne leverandøren [_1]: [_2]","You have successfully disabled automatic updates for the vendor: [_1]":"Du har deaktivert automatiske oppdateringer for leverandøren: [_1]","You have successfully disabled the vendor: [_1]":"Du har deaktivert leverandøren: [_1]","You have successfully enabled automatic updates for the vendor: [_1]":"Du har aktivert automatiske oppdateringer for leverandøren: [_1]","You have successfully enabled the vendor: [_1]":"Du har aktivert leverandøren: [_1]","You have successfully installed the vendor: [_1]":"Du har installert leverandøren: [_1]","You have successfully removed the vendor: [_1]":"Du har fjernet leverandøren: [_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
