#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/buildpureftproot                Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use Cpanel::FtpUtils::PureFTPd ();
use Digest::MD5                ();    # for speed

my ( $ok, $msg ) = Cpanel::FtpUtils::PureFTPd::build_pureftpd_roots();
die $msg if !$ok;
