#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/checkusers                      Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

# This is really a placeholder for more extensive tests of system accounts required
# by cPanel.

print "Homedir: " . ( getpwnam('cpanel') )[7] . "\n";

if ( ( getpwnam('cpanel') )[7] eq '/usr/local/cpanel/cpanel' ) {
    if ( -x '/usr/sbin/usermod' ) {
        system '/usr/sbin/usermod', '-d', '/usr/local/cpanel', 'cpanel';    # order matters
    }
    elsif ( -x '/usr/sbin/pw' ) {
        system '/usr/sbin/pw', 'usermod', 'cpanel', '-d', '/usr/local/cpanel';    # order matters
    }
}
