#!/bin/bash

# can be removed in 104

>&2 echo "Warning: This script is deprecated and will be removed in 11.104, please use 'scripts/check_cpanel_pkgs' instead."

exec /usr/local/cpanel/scripts/check_cpanel_pkgs "$@"
