#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/configure_firewall_for_cpanel   Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::configure_firewall_for_cpanel;

use strict;
use Cpanel::Services::Firewall ();

exit( Cpanel::Services::Firewall::setup_firewall() || 0 );
