#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/convert2dovecot                 Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

# This script had been superceeded by /usr/local/cpanel/scripts/setupmailserver

if ( !-x '/usr/local/cpanel/scripts/setupmailserver' ) {
    print "/usr/local/cpanel/scripts/setupmailserver is missing, conversion cannot be performed\n";
    exit(1);
}

exec( '/usr/local/cpanel/scripts/setupmailserver', 'dovecot' );
