#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/copy_user_mail_as_root          Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::copy_user_mail_as_root;

use cPstrict;

=encoding utf-8

=head1 NAME

F<scripts/copy_user_mail_as_root>

=head1 USAGE

    copy_user_mail_as_root --mode=<mode> <hostname> <username>

See F<scripts/copy_user_mail_as_user> for usage details.

=head1 DESCRIPTION

This script copies mail for a given user to or from a remote host.
It prompts for a C<root> API token for the remote host.

=cut

#----------------------------------------------------------------------

use parent (
    'Cpanel::CLI::CopyUserMail',
);

use Cpanel::Imports;

use constant {
    _APPLICATION         => 'whm',
    _get_remote_username => 'root',
};

__PACKAGE__->new(@ARGV)->run() if !caller;

#----------------------------------------------------------------------

sub _get_token_phrase ( $self, $hostname, $ ) {
    return locale()->maketext( 'Provide a [asis,root] [asis,API] token for “[_1]”:', $hostname ),;
}

1;
