#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/cpanpingtest                    Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use Cpanel::PingTest ();

$| = 1;
my $basedir   = $> == 0 ? '/home' : ( getpwuid($>) )[7];
my $cpcpandir = "$basedir/.cpcpan/";

if ( my @HOSTLIST = @ARGV ) {
    my $rPINGTIMES = Cpanel::PingTest::pinghosts( \@ARGV, 1 );

    foreach my $host (@HOSTLIST) {
        if ( !exists $rPINGTIMES->{$host} ) { next; }

        if ( open my $pingtime_fh, '>', $cpcpandir . 'pingtimes/' . $host ) {
            print {$pingtime_fh} $rPINGTIMES->{$host};
            close $pingtime_fh;
        }
        else {
            warn "Unable to write ${cpcpandir}pingtimes/$host: $!";
        }
    }
}
