#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/detect_env_capabilities         Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use Cpanel::OSSys::Capabilities ();

my $capabilities = Cpanel::OSSys::Capabilities->detect;

Cpanel::OSSys::Capabilities->save($capabilities);
