#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/dumpquotas                      Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use Cpanel::SysQuota ();

my ( $qrused, $qrlimit ) = Cpanel::SysQuota::analyzerepquotadata();

exit if !$qrused || !keys %{$qrused};

print "# dumpquotas v1\n";

foreach my $user ( keys %{$qrused} ) {
    print $user . '=' . $qrused->{$user} . "\n";
}
