#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/dumpstor                        Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use Fcntl                       ();
use Data::Dumper                ();
use Cpanel::SafeStorable        ();
use Cpanel::ConfigFiles::Apache ();

my $apacheconf = Cpanel::ConfigFiles::Apache->new();
my $file_conf  = $apacheconf->file_conf();

if ( defined $ARGV[0] && -e $ARGV[0] ) {
    print Data::Dumper::Dumper( Cpanel::SafeStorable::retrieve( $ARGV[0] ) );
}
else {
    print "This tool is for displaying the contents of a perl storable file.\n";
    print "Example: $0 $file_conf.datastore\n\n";
    print "Usage: $0 [perl storable file]\n";
}
