#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/dumpinodes                      Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use Cpanel::SysQuota ();

my ( $qrused, $qrlimit, $version, $inodes_used, $inodes_limit ) = Cpanel::SysQuota::analyzerepquotadata();

exit if !$inodes_used || !keys %{$inodes_used};

print "# dumpinodes v1\n";

foreach my $user ( keys %{$inodes_used} ) {
    print $user . '=' . $inodes_used->{$user} . "\n";
}
