#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/ensure_includes                 Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

use Cpanel::Logger ();

my $logger = Cpanel::Logger->new();

$logger->warn("ensure_includes is not supported for EasyApache 4, please edit config files as detailed in the EasyApache 4 documentation.");
exit 1;
