#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/eximstats_spam_check            Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::eximstats_spam_check;

use strict;
use warnings;

use Cpanel::EximStats::SpamCheck ();

=head1 NAME

scripts::eximstats_spam_check

=head1 SYNOPSIS

    /usr/local/cpanel/scripts/eximstats_spam_check

=head1 DESCRIPTION

This script is used to query the eximstats database, and report possible
spammers.

=cut

run() if !caller();

sub run {
    local $@;
    my $ok = eval { Cpanel::EximStats::SpamCheck::run_spammer_check() };
    die $@ if $@;
    exit 0 if ($ok);
    exit 1;
}

1;
