#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/expunge_expired_pkgacct_sessions
#                                                  Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;

package scripts::expunge_expired_pkgacct_sessions;

use Whostmgr::Backup::Pkgacct::Logs ();

if ( !caller() ) {
    run(@ARGV);

    exit 0;
}

sub run {

    my $expunge = scripts::expunge_expired_pkgacct_sessions->new();
    return $expunge->script();
}

sub new {
    my $self = bless {}, __PACKAGE__;

    return $self;
}

sub script {

    Whostmgr::Backup::Pkgacct::Logs::expunge_expired_logs();

    return 1;
}

1;
