#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/fetchfile                       Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

exec '/usr/local/cpanel/scripts/cpfetch', @ARGV;

exit 0;
