#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/fixheaders                      Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use Cpanel::SysPkgs ();

my $syspkgobj = Cpanel::SysPkgs->new();
if ( !$syspkgobj ) { die print "Could not create SysPkgs object\n"; }
my @pkgs = ('glibc-devel');

$syspkgobj->install( 'pkglist' => \@pkgs );
