#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/fixtar                          Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use Cpanel::Tar ();

my ( $tar_status, $tar_message ) = Cpanel::Tar::checkperm();
if ( !$tar_status ) {
    exit 1;
}

exit 0;
