#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel12 - ftpupdate             Copyright(c) 1997-2020 cPanel, L.L.C.
#                                 All rights reserved.
# copyright@cpanel.net              http://cpanel.net

exec '/usr/local/cpanel/bin/ftpupdate';
