#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/generate_google_drive_credentials
#                                                  Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::generate_google_drive_credentials;

use strict;
use warnings;

use Cpanel::Transport::Files::GoogleDrive::AuthHandler ();

my $code  = $ENV{'GOOGLE_AUTH_CODE'};
my $state = $ENV{'GOOGLE_AUTH_STATE'};

if ( !$code ) {

    print "Usage:  $0\n";
    print "Authorization code is passed in via environment variable:  GOOGLE_AUTH_CODE\n";
    print "Authorization state is passed in via environment variable:  GOOGLE_AUTH_STATE\n";
    exit 1;
}

my ( $rc, $message ) = Cpanel::Transport::Files::GoogleDrive::AuthHandler::generate_credential_file( $code, $state );

if ($rc) {
    print "Credentials successfully generated\n";
}
else {
    print "Google returned with the following error:  $message\n";
}
