#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/generate_google_drive_oauth_uri Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::generate_google_drive_oauth_uri;

use strict;
use warnings;

use Cpanel::Transport::Files::GoogleDrive::AuthHandler ();

my $client_id     = $ENV{'GOOGLE_CLIENT_ID'};
my $client_secret = $ENV{'GOOGLE_CLIENT_SECRET'};

if ( !$client_id || !$client_secret ) {

    print "Usage:  $0\n";
    print "Client ID is passed in via environment variable:  GOOGLE_CLIENT_ID\n";
    print "Client secret is passed in via environment variable:  GOOGLE_CLIENT_SECRET\n";
    exit 1;
}

print Cpanel::Transport::Files::GoogleDrive::AuthHandler::generate_google_oauth_uri_and_save_params( $client_id, $client_secret );
