#!/bin/bash

# cpanel - scripts/initfpsuexec                    Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

# this script is needed by Easy Apache, which calls it blindly
# so simply do nothing when called

exit 0
