#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/installpkg                      Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;
use Cpanel::SysPkgs ();

my $syspkgobj = Cpanel::SysPkgs->new();
if ( !$syspkgobj ) { die print "Could not create SysPkgs object\n"; }
$syspkgobj->install( 'pkglist' => \@ARGV );
exit;
