#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/isdedicatedip                   Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;
use Cpanel::DIp::IsDedicated ();

my $res = ( Cpanel::DIp::IsDedicated::isdedicatedip( $ARGV[0] ) );
if ($res) {
    print "$ARGV[0] is a dedicated IP\n";
}
else {
    print "$ARGV[0] is NOT a dedicated IP\n";
}
