#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/killmysqluserprivs              Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;

exec '/usr/local/cpanel/bin/killmysqluserprivs', @ARGV;
