#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/listsubdomains                  Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;

use Cpanel::Config::LoadUserOwners ();
use Cpanel::Config::userdata       ();

my $user = $ARGV[0];

if ( !defined $user ) {
    &usage;
}

my @users = ($user);

# Case 41981: For resellers, add their client users' accounts
my %OWNER;
Cpanel::Config::LoadUserOwners::loadtrueuserowners( \%OWNER, 1, 1 );
push @users, ( grep { $OWNER{$_} eq $users[0] && $_ ne $users[0] } keys(%OWNER) );

foreach $user (@users) {
    print $user, ":\n";
    my $subdomains_hr = Cpanel::Config::userdata::load_user_subdomains($user);

    for my $subdomain ( keys %$subdomains_hr ) {
        print "\t", $subdomain, "\n";
    }
}

sub usage {
    print <<EO_USAGE;
Usage: listsubdomains user
EO_USAGE
    exit 0;
}
