#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/listcheck                       Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

if ( !-e '/var/cpanel/cp76maillists' ) {
    system '/usr/local/cpanel/scripts/resetmailmanurls';
    open( my $m_fh, '>>', '/var/cpanel/cp76maillists' );
    close $m_fh;
}
