#!/usr/bin/perl

# cpanel - scripts/perlinstaller                   Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

BEGIN {
    $ENV{'LANG'} = 'C';
    unshift @INC, '/usr/local/cpanel';
}

use Cpanel::CleanINC ();

use Cpanel::cPCPAN ();

my $cPCPAN = Cpanel::cPCPAN->new();

$cPCPAN->install(@ARGV);
