#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/rebuildippool                   Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use Cpanel::IpPool ();

my $freeips = Cpanel::IpPool::rebuild();
print "The system has $freeips free IP" . ( $freeips == 1 ? '' : 's' ) . ".\n";
