#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/restartsrv_ftpserver            Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

use Cpanel::Config::LoadCpConf ();

my $cpconf = Cpanel::Config::LoadCpConf::loadcpconf_not_copy();
if ( $cpconf->{'ftpserver'} eq 'pure-ftpd' ) {
    exec '/usr/local/cpanel/scripts/restartsrv_pureftpd', @ARGV;
}
elsif ( $cpconf->{'ftpserver'} eq 'proftpd' ) {
    exec '/usr/local/cpanel/scripts/restartsrv_proftpd', @ARGV;
}
elsif ( $cpconf->{'ftpserver'} ne 'disabled' ) {
    die "unknown ftpserver specified in /var/cpanel/cpanel.config: $cpconf->{'ftpserver'}";
}

print "The FTP server is disabled.\n";
exit(1);
