#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/restartsrv_named                Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use cPstrict;

# preserve original behavior
if ( -e '/var/cpanel/usepowerdns' ) {
    exec '/usr/local/cpanel/scripts/restartsrv_pdns', @ARGV;
}
else {
    exec '/usr/local/cpanel/scripts/restartsrv_bind', @ARGV;
}
