#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/restartsrv_imap                 Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;

exec '/usr/local/cpanel/scripts/restartsrv_dovecot', @ARGV;
