#!/bin/bash

# cpanel - scripts/run_if_exists                   Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

# used to run legacy hooks without warnings

WHAT="$1"
[ "x$WHAT" = "x" ] && exit 1;

# preserve error when file is not executable
if [ -e "$WHAT" ]; then
    exec $WHAT;
fi
