#!/bin/bash

# cpanel - scripts/runstatsonce                    Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

#This script is supposed to be run from crontab.

export IGNORELASTRUN=1
/usr/local/cpanel/cpanellogd
