#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/sync_contact_emails_to_cpanel_users_files
#                                                  Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::sync_contact_emails_to_cpanel_users_files;

use cPstrict;

=encoding utf-8

=head1 USAGE

Do not use.

=head1 DESCRIPTION

This script formerly copied contact email addresses from user-owned
contact-information datastores to the main user datastore. cPanel & WHM
no longer implements this workflow, though, so this script is now
redundant.

A future cPanel & WHM version will remove this script entirely.

=cut

#----------------------------------------------------------------------

use parent 'Cpanel::HelpfulScript';

use constant _OPTIONS => ();

#----------------------------------------------------------------------

__PACKAGE__->new(@ARGV)->run() if !caller;

sub run ($self) {
    die $self->full_help();
}

1;
