#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/sync-mysql-users-from-grants    Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::sync_mysql_users_from_grants;

use strict;
use warnings;

=encoding utf-8

=head1 NAME

sync_mysql_users_from_grants

=head1 USAGE

    sync_mysql_users_from_grants [ --help ]

=head1 DESCRIPTION

Ordinarily the system creates a DB user in MySQL/MariaDB for each cPanel user
account. If MySQL/MariaDB is disabled, however, when the account is created,
and that service is later reenabled, it is necessary to create the DB users
that the system would have created had such been possible at account creation
time.

This script fulfills that purpose.

=cut

use parent qw( Cpanel::HelpfulScript );

use Cpanel::Mysql::SyncUsers ();

use constant _OPTIONS => ();

__PACKAGE__->new(@ARGV)->run() if !caller;

sub run {
    my ($self) = @_;

    Cpanel::Mysql::SyncUsers::sync_grant_files_to_db(
        output => \*STDOUT,
    );

    return;
}

1;
