#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/sysup                           Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

use Cpanel::Sysup ();

# Run returns whether it was successful; invert for exit code

my $want_supplemental_packages = $ENV{'CPANEL_BASE_INSTALL'} ? 0 : 1;

exit( Cpanel::Sysup->new->run( supplemental_packages => $want_supplemental_packages ) ? 0 : 1 );
