#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/uninstall_dovecot_fts           Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::uninstall_dovecot_fts;

use strict;
use warnings;

use Cpanel::Plugins ();

run() if !caller;

sub run {
    return Cpanel::Plugins::uninstall_plugins('cpanel-dovecot-solr');
}

1;
