#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/update_users_jail               Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

use Cpanel::PwCache             ();
use Cpanel::JailManager::Update ();

my $user = $ARGV[0];

if ($user) {
    my @PW = Cpanel::PwCache::getpwnam($user);
    if ( !$PW[2] ) {
        print "User: $0 [user]";
        exit 1;
    }
}

Cpanel::JailManager::Update::update_users_jail($user) or exit(1);
