#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/update_known_proxy_ips          Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::update_known_proxy_ips;

=encoding utf-8

=head1 NAME

update_known_proxy_ips

=head1 USAGE

    update_known_proxy_ips [--help]

=head1 DESCRIPTION

cPanel & WHM have need for certain applications to track lists of known
HTTP proxies. Each cPanel & WHM server maintains a local list of these
proxies. This script refreshes that local list.

=cut

use strict;
use warnings;

use parent qw( Cpanel::HelpfulScript );

use Cpanel::KnownProxies::Build ();

use constant _OPTIONS => ();

__PACKAGE__->new(@ARGV)->run() if !caller;

sub run {
    my ($self) = @_;

    Cpanel::KnownProxies::Build::update();

    return;
}

1;
