#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/update_users_vhosts             Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

use Cpanel::ConfigFiles::Apache::vhost   ();
use Cpanel::HttpUtils::ApRestart::BgSafe ();

my $user = $ARGV[0];

if ( !$user ) {
    print "Usage: $0 <user>\n";
    exit 1;
}

my ( $ok, $msg ) = Cpanel::ConfigFiles::Apache::vhost::update_users_vhosts($user);
die "$msg\n" if !$ok;

print "All vhosts for user $user have been updated successfully.\n";

Cpanel::HttpUtils::ApRestart::BgSafe::restart();

exit 0;
