#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/updatedomainips                 Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

# ignore our parent if it dies as this could result in
# a blank domainips files
$SIG{'HUP'} = 'IGNORE';
$SIG{'INT'} = 'IGNORE';

use strict;

use Cpanel::DIp::Update ();

Cpanel::DIp::Update::update_dedicated_ips_and_dependencies_or_die();
