#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/update_neighbor_netblocks       Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;

use Cpanel::IP::Neighbors ();

Cpanel::IP::Neighbors::update_neighbor_netblocks_or_log() or exit(1);

exit();
