#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/update_apachectl                Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

print "Nothing to do under ea4 (this script has been deprecated under ea4).\n";
exit(0);
