#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/update_mysql_systemd_config     Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package scripts::update_mysql_systemd_config;

use strict;
use warnings;

use parent qw( Cpanel::HelpfulScript );

=encoding utf-8

=head1 USAGE

    update_mysql_systemd_config [ --help ]

=head1 DESCRIPTION

This script checks if MySQL/MariaDB's systemd configuration needs some additional options.
If so, it'll add them and do a daemon-reload and then restart MySQL/MariaDB.

=cut

use Cpanel::OS                               ();
use Cpanel::MysqlUtils::Systemd::ProtectHome ();

use constant _OPTIONS => ();

run(@ARGV) if !caller;

sub run {
    my (@args) = @_;

    my $self = __PACKAGE__->new(@args);
    return $self->script();
}

sub script {
    my ($self) = @_;

    if ( Cpanel::OS::is_systemd() ) {
        Cpanel::MysqlUtils::Systemd::ProtectHome::set_unset_protecthome_if_needed();
    }
    else {
        $self->say_maketext('This system does not use [asis,systemd].');
    }

    return 1;
}

1;
