#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - scripts/verify_api_spec_files           Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

use Cpanel::Parallelizer ();

my $parallelizer = Cpanel::Parallelizer->new( process_limit => 4 );
$parallelizer->queue( sub { require Cpanel::ApiInfo::UAPI; Cpanel::ApiInfo::UAPI->new->verify() }, [], sub { }, sub { } );
$parallelizer->queue( sub { require Cpanel::ApiInfo::Api2; Cpanel::ApiInfo::Api2->new->verify() }, [], sub { }, sub { } );
$parallelizer->run();
