//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/libraries/cjt2/src/views/applicationController.js
// Generated: /usr/local/cpanel/share/libraries/cjt2/src/views/applicationController-pt_br.js
// Module:    cjt/views/applicationController-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system failed to change the route with the following error: [_1] - [_2]":"O sistema falhou em alterar a rota com o seguinte erro: [_1] - [_2]","The system failed to change the route, but there is no information about the error.":"O sistema falhou em alterar a rota, mas não há informações sobre o erro.","Your session may have expired or you logged out of the system. [output,url,_1,Log in] again to continue.":"Sua sessão pode ter expirado ou você se desconectou do sistema. [output,url,_1,Faça login] novamente para continuar."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
