//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/libraries/cjt2/src/views/applicationController.js
// Generated: /usr/local/cpanel/share/libraries/cjt2/src/views/applicationController-ro.js
// Module:    cjt/views/applicationController-ro
// Locale:    ro
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system failed to change the route with the following error: [_1] - [_2]":"Sistemul nu a reuşit să schimbe ruta, generând următoarea eroare: [_1] - [_2]","The system failed to change the route, but there is no information about the error.":"Sistemul nu a reuşit să modifice ruta, dar nu există informaţii despre eroare.","Your session may have expired or you logged out of the system. [output,url,_1,Log in] again to continue.":"Este posibil ca sesiunea dvs. să fi expirat sau v-aţi deconectat de la sistem. [output,url,_1,Conectaţi-vă] din nou pentru a continua."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
