<ol class="task-list">
    <li class="task" ng-repeat="item in tasks">
        <table>
            <tr ng-repeat="(key, label) in ::taskAttributeLabel" ng-if="(item[key] !== undefined) && ($parent.$parent.$parent.showDetails || alwaysShow[key])">
                <th class="task-parameter">{{::label}}:</th>
                <td ng-if="::isArray(item[key])">
                    <span class="task-arg" ng-repeat="arg in ::item[key]">{{::arg}}</span>
                </td>
                <td ng-if="::!isArray(item[key])">{{::item[key]}}</td>
            </tr>
        </table>
    </li>
</ol>
