//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/external_auth/views/ConfigureProviderController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/external_auth/views/ConfigureProviderController-es_es.js
// Module:    /templates/external_auth/views/ConfigureProviderController-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system could not update the configurations for “[_1].” The following error occurred: “[_2]”":"El sistema no pudo actualizar las configuraciones para “[_1].” Se produjo el siguiente error: “[_2]”","The system successfully updated the configurations for “[_1].”":"El sistema actualizó las configuraciones para “[_1]” correctamente."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
