//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/ruleService.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/ruleService-fil.js
// Module:    /templates/mod_security/services/ruleService-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"You have successfully added the rule to the staged configuration file.":"Matagumpay mo nang nadagdag ang rule sa staged configuration file.","You have successfully deployed the staged rules to your custom [asis,ModSecurity™] configuration.":"Matagumpay mong na-deploy ang mga staged rule sa iyong custom [asis,ModSecurity™] configuration.","You have successfully disabled the rule.":"Matagumpay mong na-disable ang rule.","You have successfully enabled the rule.":"Matagumpay mong na-enable ang rule.","You have successfully updated the rule in the staged configuration file.":"Matagumpay mong na-update ang rule sa staged configuration file."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
