//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/ruleService.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/ruleService-es.js
// Module:    /templates/mod_security/services/ruleService-es
// Locale:    es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"You have successfully added the rule to the staged configuration file.":"Agregó la regla al archivo de configuración predeterminado correctamente.","You have successfully deployed the staged rules to your custom [asis,ModSecurity™] configuration.":"Implementó las reglas preconfiguradas a la configuración personalizada de [asis,ModSecurity™] correctamente.","You have successfully disabled the rule.":"Deshabilitó la regla correctamente.","You have successfully enabled the rule.":"Habilitó la regla correctamente.","You have successfully updated the rule in the staged configuration file.":"Actualizó la regla en el archivo de confirmación predeterminado correctamente."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
