//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/ruleService.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/ruleService-ro.js
// Module:    /templates/mod_security/services/ruleService-ro
// Locale:    ro
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"You have successfully added the rule to the staged configuration file.":"Aţi adăugat cu succes regula la fişierul de configurare etapizat.","You have successfully deployed the staged rules to your custom [asis,ModSecurity™] configuration.":"Aţi implementat cu succes regulile etapizate la configuraţia [asis,ModSecurity™] particularizată.","You have successfully disabled the rule.":"Aţi dezactivat cu succes regula.","You have successfully enabled the rule.":"Aţi activat cu succes regula.","You have successfully updated the rule in the staged configuration file.":"Aţi actualizat cu succes regula din fişierul de configurare etapizat."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
