//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/ruleService.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/ruleService-th.js
// Module:    /templates/mod_security/services/ruleService-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"You have successfully added the rule to the staged configuration file.":"คุณได้เพิ่มกฎลงในไฟล์การกำหนดค่าตามขั้นตอนเรียบร้อยแล้ว","You have successfully deployed the staged rules to your custom [asis,ModSecurity™] configuration.":"คุณได้ปรับใช้กฎตามขั้นตอนไปยังการกำหนดค่า [asis,ModSecurity™] ที่กำหนดเองเรียบร้อยแล้ว","You have successfully disabled the rule.":"คุณได้ปิดใช้งานกฎเรียบร้อยแล้ว","You have successfully enabled the rule.":"คุณได้เปิดใช้งานกฎเรียบร้อยแล้ว","You have successfully updated the rule in the staged configuration file.":"คุณได้อัพเดตกฎในไฟล์การกำหนดค่าตามขั้นตอนเรียบร้อยแล้ว"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
