//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/vendorService.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mod_security/services/vendorService-ar.js
// Module:    /templates/mod_security/services/vendorService-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system could not find the specified [asis,vendor_id].":"يتعذر على النظام العثور على [asis,vendor_id] المحدد.","You have multiple vendors with the same [asis,vendor_id].":"لديك العديد من الموردين باسم [asis,vendor_id]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
