//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/transfer_tool/overwriteOptions.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/transfer_tool/overwriteOptions-de.js
// Module:    /templates/transfer_tool/overwriteOptions-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Do Not Overwrite":"Nicht überschreiben","Overwrite":"Überschreiben","Overwrite with Delete":"Überschreiben und löschen"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
