//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/version_control/views/listRepositoriesController.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/version_control/views/listRepositoriesController-id.js
// Module:    /jupiter/version_control/views/listRepositoriesController-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Are you sure that you want to remove the “[_1]” repository from the list of [asis,cPanel]-managed repositories?":"Yakin ingin menghapus repositori “[_1]” dari daftar repositori yang dikelola [asis,cPanel]?","Error occurred while cloning repository “[_1]”.":"Kesalahan terjadi ketika mengklonakan repositori “[_1]”.","The system could not remove the “[_1]” repository in the “[_2]” directory.":"Sistem tidak dapat menghapus repositori “[_1]” dalam direktori “[_2]”.","The system successfully copied the “[_1]” clone [output,acronym,URL,Uniform Resource Locator] to the clipboard.":"Sistem berhasil menyalin klona “[_1]” [output,acronym,URL,Uniform Resource Locator] ke papan klip.","The system successfully removed the “[_1]” repository from the list of [asis,cPanel]-managed repositories.":"Sistem berhasil menghapus repositori “[_1]” dari daftar repositori terkelola [asis,cPanel].","The system successfully removed the “[_1]” repository from the list of [asis,cPanel]-managed repositories. You can use the [output,url,_2,File Manager,target,_3] interface to delete the repository contents.":"The system successfully removed the “[_1]” repository from the list of [asis,cPanel]-managed repositories. You can use the [output,url,_2,File Manager,target,_3] interface to delete the repository contents.","Unable to find repository web url":"Tidak dapat menemukan url web repositori","Unable to redirect to File Manager interface":"Tidak dapat mengarahkan ulang ke antarmuka Pengelola File"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
