//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/tls_wizard_redirect/views/purchaseRedirectController.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/tls_wizard_redirect/views/purchaseRedirectController-zh.js
// Module:    /templates/tls_wizard_redirect/views/purchaseRedirectController-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Because no other providers are enabled, the system enabled the [asis,cPanel Store] provider.":"因为没有启用其他提供商，系统启用了 [asis,cPanel Store] 提供商。","Click to continue as the “[_1]” user and purchase an [asis,SSL] certificate.":"单击以“[_1]”用户的身份继续操作并购买 [asis,SSL] 许可证。","Displaying [numf,_1] to [numf,_2] out of [quant,_3,item,items]":"正在显示 [numf,_1] 至 [numf,_2] 项，共 [quant,_3,个项目,个项目]","The system changed the theme for user “[_1]” to “[_2]”, with the “[asis,Retro]” style, to support this feature.":"The system changed the theme for user “[_1]” to “[_2]”, with the “[asis,Retro]” style, to support this feature.","The system enabled the [numerate,_1,feature,features] [list_and_quoted,_2] for the user “[_3]” to ensure access to the “[_4]”.":"系统已经为用户“[_3]”启用了 [numerate,_1,功能,功能] [list_and_quoted,_2] 以确保对“[_4]”的访问权。","The system failed to fetch the user’s account information because of the following error: [_1]":"由于以下错误，系统未能提取用户的帐户信息: [_1]","You cannot redirect to this account because it does not have theme support for this feature.":"您无法重定向至此帐户，因为其没有支持此功能的主题。","[asis,SSL]/[asis,TLS] Wizard":"[asis,SSL]/[asis,TLS] 向导"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
