//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mysqlhost/index.cmb.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mysqlhost/index.cmb-it.js
// Module:    /templates/mysqlhost/index.cmb-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Activation completed for “[_1]”.":"Attivazione completata per “[_1]”.","Activation failed for “[_1]” during step “[_2]” because of an error: [_3]":"Activation failed for “[_1]” during step “[_2]” because of an error: [_3]","Activation in progress for “[_1]”.":"Attivazione in corso per “[_1]”.","An unexpected error occurred.":"Si è verificato un errore imprevisto.","The host must be a valid [asis,IP] address or [asis,hostname].":"L’host deve essere un indirizzo [asis,IP] o [asis,hostname] valido.","The profile “[_1]” is valid.":"Il profilo “[_1]” non è valido.","The value must be a valid [asis,loopback] address.":"Il valore deve essere un indirizzo [asis,loopback] valido.","This step completed.":"Passaggio completato.","This step failed.":"Passaggio non riuscito.","This step is in progress.":"Passaggio in corso.","This step was skipped.":"Questo passaggio è stato ignorato.","You have successfully created the profile, “[_1]”.":"Creazione profilo “[_1]” completata.","You have successfully deleted the profile, “[_1]”.":"Eliminazione profilo “[_1]” completata.","You have successfully updated the profile, “[_1]”.":"Aggiornamento profilo “[_1]” completato."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
