//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/mysqlhost/index.cmb.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/mysqlhost/index.cmb-fr.js
// Module:    /templates/mysqlhost/index.cmb-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Activation completed for “[_1]”.":"Activation terminée pour « [_1] ».","Activation failed for “[_1]” during step “[_2]” because of an error: [_3]":"Activation failed for “[_1]” during step “[_2]” because of an error: [_3]","Activation in progress for “[_1]”.":"Activation en cours pour « [_1] ».","An unexpected error occurred.":"Une erreur inattendue s’est produite.","The host must be a valid [asis,IP] address or [asis,hostname].":"L’hôte doit être une adresse [asis,IP] ou un [asis,hostname] valide.","The profile “[_1]” is valid.":"Le profil « [_1] » est valide.","The value must be a valid [asis,loopback] address.":"La valeur doit être une adresse [asis,loopback] valide.","This step completed.":"Cette étape est terminée.","This step failed.":"Cette étape a échoué.","This step is in progress.":"Cette étape est en cours.","This step was skipped.":"Cette étape a été ignorée.","You have successfully created the profile, “[_1]”.":"Vous avez créé le profil « [_1] ».","You have successfully deleted the profile, “[_1]”.":"Vous avez supprimé le profil « [_1] ».","You have successfully updated the profile, “[_1]”.":"Vous avez mis à jour le profil « [_1] »."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
