//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/libraries/cjt2/src/directives/whm/userDomainListDirective.js
// Generated: /usr/local/cpanel/share/libraries/cjt2/src/directives/whm/userDomainListDirective-zh.js
// Module:    cjt/directives/whm/userDomainListDirective-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A list of users and domains from which to choose.":"A list of users and domains from which to choose.","Account Summary for the “[_1]” user.":"Account Summary for the “[_1]” user.","All":"全部","Bandwidth":"带宽","CGI Access?":"CGI Access?","Databases":"数据库","Dedicated IP?":"专用 IP?","Disk Usage":"磁盘使用情况","Domains":"域","Email Accounts":"电子邮件帐户","Email Addresses":"Email Addresses","Email Lists":"电子邮件列表","FTP Accounts":"FTP 帐户","Feature List":"功能列表","Loading Account Summary …":"Loading Account Summary …","No":"否","No results found that match “[_1]”…":"No results found that match “[_1]”…","No results found with a domain that match “[_1]”…":"No results found with a domain that match “[_1]”…","No results found with a username that match “[_1]”…":"No results found with a username that match “[_1]”…","No results found…":"No results found…","Owner":"所有者","Package":"资源包","Package “[_1]” for user “[_2]”":"Package “[_1]” for user “[_2]”","Quota":"配额","Search By:":"搜索标准:","Search by both users and domains.":"Search by both users and domains.","Search by domains only.":"Search by domains only.","Search by users only.":"Search by users only.","Search for a user or a domain.":"Search for a user or a domain.","Select the “[_1]” user and the ”[_2]” domain.":"Select the “[_1]” user and the ”[_2]” domain.","Select the “[_1]” user.":"Select the “[_1]” user.","Select this user.":"Select this user.","Shell access?":"Shell 访问?","Start Date":"开始日期","Subdomains":"子域","The system failed to load the account summary.":"The system failed to load the account summary.","Theme":"主题","User Editing Locked:":"User Editing Locked:","Users":"用户","Yes":"是","[asis,IP] Address":"[asis,IP] Address","cPanel Theme":"cPanel 主题","unknown":"未知"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
