//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/share/libraries/cjt2/src/directives/whm/userDomainListDirective.js
// Generated: /usr/local/cpanel/share/libraries/cjt2/src/directives/whm/userDomainListDirective-ro.js
// Module:    cjt/directives/whm/userDomainListDirective-ro
// Locale:    ro
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A list of users and domains from which to choose.":"A list of users and domains from which to choose.","Account Summary for the “[_1]” user.":"Account Summary for the “[_1]” user.","All":"Toate","Bandwidth":"Lăţime de bandă","CGI Access?":"CGI Access?","Databases":"Baze de date","Dedicated IP?":"IP-ul este dedicat?","Disk Usage":"Utilizare disc","Domains":"Domenii","Email Accounts":"Conturi de e-mail","Email Addresses":"Email Addresses","Email Lists":"Liste de e-mail","FTP Accounts":"Conturi FTP","Feature List":"Listă de caracteristici","Loading Account Summary …":"Loading Account Summary …","No":"Nu","No results found that match “[_1]”…":"No results found that match “[_1]”…","No results found with a domain that match “[_1]”…":"No results found with a domain that match “[_1]”…","No results found with a username that match “[_1]”…":"No results found with a username that match “[_1]”…","No results found…":"No results found…","Owner":"Proprietar","Package":"Pachet","Package “[_1]” for user “[_2]”":"Package “[_1]” for user “[_2]”","Quota":"Cotă","Search By:":"Căutare după:","Search by both users and domains.":"Search by both users and domains.","Search by domains only.":"Search by domains only.","Search by users only.":"Search by users only.","Search for a user or a domain.":"Search for a user or a domain.","Select the “[_1]” user and the ”[_2]” domain.":"Select the “[_1]” user and the ”[_2]” domain.","Select the “[_1]” user.":"Select the “[_1]” user.","Select this user.":"Select this user.","Shell access?":"Acces la shell?","Start Date":"Data de început","Subdomains":"Subdomenii","The system failed to load the account summary.":"The system failed to load the account summary.","Theme":"Temă","User Editing Locked:":"User Editing Locked:","Users":"Utilizatori","Yes":"Da","[asis,IP] Address":"[asis,IP] Address","cPanel Theme":"Temă cPanel","unknown":"necunoscut"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
