//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/mail/spam/services/spamAssassin.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/mail/spam/services/spamAssassin-es_es.js
// Module:    /jupiter/mail/spam/services/spamAssassin-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All Spam Box folders expunged.":"Se han eliminado todas las carpetas de Spam Box.","Expunged the Spam Box folder for “[_1]”.":"Se eliminó la carpeta Spam Box para “[_1]”.","Spam Auto-Delete has been disabled.":"La eliminación automática de spam ha sido desactivada.","Spam Auto-Delete has been enabled.":"La eliminación automática de spam ha sido activada.","Spam Box has been disabled.":"Spam Box ha sido desactivado.","Spam Box has been enabled.":"Spam Box ha sido activado.","The Auto-Delete Threshold Score has been updated to [_1].":"La puntuación umbral de eliminación automática se ha actualizado a [_1].","The [asis,Apache SpamAssassin] user preferences have been updated.":"Las preferencias de usuario de [asis,Apache SpamAssassin] han sido actualizadas.","[asis,Apache SpamAssassin] has been disabled.":"[asis,Apache SpamAssassin] ha sido desactivado.","[asis,Apache SpamAssassin] has been enabled.":"[asis,Apache SpamAssassin] ha sido activado."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
