//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/backup/restore.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/backup/restore-cs.js
// Module:    /templates/backup/restore-cs
// Locale:    cs
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Adding “[_1]” to the restoration queue …":"Přidává se „[_1]“ do fronty obnovení…","Completed":"Dokončeno","Completed with warnings":"Dokončeno s upozorněními","Could not add “[_1]” to the restoration queue ([_2]).":"Nelze přidat „[_1]“ do fronty obnovení ([_2]).","Could not clear completed restorations.":"Nelze smazat dokončená obnovení.","Could not clear failed restorations.":"Nelze smazat nezdařená obnovení.","Could not clear pending restorations.":"Nelze smazat nevyřízená obnovení.","Could not clear the restoration queue.":"Nelze smazat frontu obnovení.","Could not remove “[_1]” from the finished list ([_2]).":"Nelze odebrat „[_1]“ z dokončeného seznamu ([_2]).","Could not remove “[_1]” from the restoration queue ([_2]).":"Nelze odebrat „[_1]“ z fronty obnovení ([_2]).","Could not restore account “[_1]”: [_2]":"Nelze obnovit účet „[_1]“: [_2]","Could not start the restoration queue.":"Nelze spustit frontu obnovení.","Failed":"Chyba","Failed to retrieve the restore queue state.":"Nepodařilo se načíst stav fronty obnovení.","No log is available because the restore failed.":"Žádný protokol není k dispozici, protože obnovení se nezdařilo.","Pending":"Nevyřízené","Restoring Account":"Obnovení účtu","The log file for the restore of user “[_1]” is empty.":"Soubor protokolu pro obnovení uživatele [_1] je prázdný.","Unknown Error":"Neznámá chyba","Your browser may have blocked the request, or your connection may be unstable":"Your browser may have blocked the request, or your connection may be unstable"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
