//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/backup/restore.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/backup/restore-zh.js
// Module:    /templates/backup/restore-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Adding “[_1]” to the restoration queue …":"正在将“[_1]”添加到还原队列…","Completed":"已完成","Completed with warnings":"完成并显示警告","Could not add “[_1]” to the restoration queue ([_2]).":"无法将“[_1]”添加到还原队列([_2])。","Could not clear completed restorations.":"无法清除完成的还原。","Could not clear failed restorations.":"无法清除失败的还原。","Could not clear pending restorations.":"无法清除挂起的还原。","Could not clear the restoration queue.":"无法清除还原队列。","Could not remove “[_1]” from the finished list ([_2]).":"无法从完成的列表([_2])删除“[_1]”。","Could not remove “[_1]” from the restoration queue ([_2]).":"无法从还原队列中删除“[_1]”([_2])。","Could not restore account “[_1]”: [_2]":"无法还原帐户“[_1]”: [_2]","Could not start the restoration queue.":"无法启动还原队列。","Failed":"失败","Failed to retrieve the restore queue state.":"无法检索还原队列状态。","No log is available because the restore failed.":"因为还原失败，无日志可用。","Pending":"挂起","Restoring Account":"正在还原帐户","The log file for the restore of user “[_1]” is empty.":"还原用户“[_1]”的日志文件为空。","Unknown Error":"未知错误","Your browser may have blocked the request, or your connection may be unstable":"Your browser may have blocked the request, or your connection may be unstable"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
