//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/backup/restore.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/backup/restore-hu.js
// Module:    /templates/backup/restore-hu
// Locale:    hu
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Adding “[_1]” to the restoration queue …":"„[_1]” hozzáadása a helyreállítási sorhoz…","Completed":"Befejeződött","Completed with warnings":"Kész, figyelmeztetésekkel","Could not add “[_1]” to the restoration queue ([_2]).":"A(z) „[_1]” nem adható hozzá a helyreállítási sorhoz ([_2])","Could not clear completed restorations.":"A befejezett helyreállítások nem törölhetők.","Could not clear failed restorations.":"A sikertelen helyreállítások nem törölhetők.","Could not clear pending restorations.":"A függőben levő helyreállítások nem törölhetők.","Could not clear the restoration queue.":"A helyreállítási sor nem törölhető.","Could not remove “[_1]” from the finished list ([_2]).":"A(z) „[_1]” nem távolítható el a befejezett listából ([_2]).","Could not remove “[_1]” from the restoration queue ([_2]).":"A(z) „[_1]” nem távolítható el a helyreállítási sorból ([_2]).","Could not restore account “[_1]”: [_2]":"A(z) „[_1]” fiók nem állítható helyre: [_2]","Could not start the restoration queue.":"A helyreállítási sor nem kezdhető el.","Failed":"Sikertelen","Failed to retrieve the restore queue state.":"Nem sikerült lekérdezni a visszaállítási sor állapotát.","No log is available because the restore failed.":"Nincs elérhető napló, mert nem sikerült a visszaállítás.","Pending":"Függőben","Restoring Account":"Fiók visszaállítása","The log file for the restore of user “[_1]” is empty.":"A(z) „[_1]” felhasználó visszaállításának naplófájlja üres.","Unknown Error":"Ismeretlen hiba","Your browser may have blocked the request, or your connection may be unstable":"Your browser may have blocked the request, or your connection may be unstable"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
