//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/backup/restore.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/backup/restore-ru.js
// Module:    /templates/backup/restore-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Adding “[_1]” to the restoration queue …":"Adding “[_1]” to the restoration queue …","Completed":"Завершено","Completed with warnings":"Завершено с ошибками","Could not add “[_1]” to the restoration queue ([_2]).":"Could not add “[_1]” to the restoration queue ([_2]).","Could not clear completed restorations.":"Очистить завершенные восстановления не удалось.","Could not clear failed restorations.":"Очистить неудачно завершенные восстановления не удалось.","Could not clear pending restorations.":"Очистить ожидаемые восстановления не удалось.","Could not clear the restoration queue.":"Очистить очередь восстановлений не удалось.","Could not remove “[_1]” from the finished list ([_2]).":"Could not remove “[_1]” from the finished list ([_2]).","Could not remove “[_1]” from the restoration queue ([_2]).":"Could not remove “[_1]” from the restoration queue ([_2]).","Could not restore account “[_1]”: [_2]":"Could not restore account “[_1]”: [_2]","Could not start the restoration queue.":"Запустить очередь восстановлений не удалось.","Failed":"Ошибка","Failed to retrieve the restore queue state.":"Получить состояние очереди восстановления не удалось.","No log is available because the restore failed.":"Доступных журналов нет из-за сбоя восстановления.","Pending":"Ожидание","Restoring Account":"Восстановление учетной записи","The log file for the restore of user “[_1]” is empty.":"The log file for the restore of user “[_1]” is empty.","Unknown Error":"Неизвестная ошибка","Your browser may have blocked the request, or your connection may be unstable":"Возможно, ваш браузер заблокировал запрос, или ваше подключение нестабильно."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
