//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/backup/restore.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/backup/restore-id.js
// Module:    /templates/backup/restore-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Adding “[_1]” to the restoration queue …":"Menambahkan “[_1]” ke antrean pemulihan …","Completed":"Selesai","Completed with warnings":"Selesai dengan peringatan","Could not add “[_1]” to the restoration queue ([_2]).":"Tidak dapat menambahkan “[_1]” ke antrean pemulihan ([_2]).","Could not clear completed restorations.":"Tidak dapat menghapus pemulihan yang selesai.","Could not clear failed restorations.":"Tidak dapat menghapus pemulihan yang gagal.","Could not clear pending restorations.":"Tidak dapat menghapus pemulihan yang tertunda.","Could not clear the restoration queue.":"Tidak dapat menghapus antrean pemulihan.","Could not remove “[_1]” from the finished list ([_2]).":"Tidak dapat menghapus “[_1]” dari daftar selesai ([_2]).","Could not remove “[_1]” from the restoration queue ([_2]).":"Tidak dapat menghapus “[_1]” dari antrean pemulihan ([_2]).","Could not restore account “[_1]”: [_2]":"Tidak dapat memulihkan akun “[_1]”: [_2]","Could not start the restoration queue.":"Tidak dapat memulai antrean pemulihan.","Failed":"Gagal","Failed to retrieve the restore queue state.":"Gagal mendapatkan status antrean pemulihan.","No log is available because the restore failed.":"Tidak ada log yang tersedia karena pemulihan gagal.","Pending":"Tertunda","Restoring Account":"Memulihkan Akun","The log file for the restore of user “[_1]” is empty.":"File log untuk pemulihan pengguna “[_1]” kosong.","Unknown Error":"Kesalahan Tidak Dikenal","Your browser may have blocked the request, or your connection may be unstable":"Browser Anda mungkin telah memblokir permintaan tersebut, atau koneksi Anda mungkin tidak stabil"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
