//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/js2/ssl/install-pl.js
// Module:    /jupiter/js2/ssl/install-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"Akcje","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"Czy na pewno chcesz usunąć hosta SSL „[_1]”? Tej operacji nie będzie można cofnąć!","Certificate Expiration":"Wygaśnięcie ważności certyfikatu","Confirm SSL Host Delete":"Potwierdzanie usunięcia hosta SSL","Deleting SSL host “[_1]” …":"Usuwanie hosta SSL „[_1]”…","Document Root":"Katalog główny dokumentu","Is Primary Website on IP Address?":"Czy to podstawowa witryna internetowa na tym adresie IP?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"Czy jest wymagany mechanizm [output,acronym,SNI,Server Name Indication] do usług sieci Web?","Loading …":"Ładowanie…","No":"Nie","Setting “[_1]” as the primary SSL host …":"Setting “[_1]” as the primary SSL host …","The SSL host for “[_1]” has been removed.":"Host SSL domeny „[_1]” został usunięty.","Yes":"Tak","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You don’t have a dedicated IP address. Browsers that were released before 2013 may not support [output,abbr,SNI,Server Name Indication]. Because of this, users may see false security warnings when they visit your SSL-secured websites.":"[output,strong,Note:] You don’t have a dedicated IP address. Browsers that were released before 2013 may not support [output,abbr,SNI,Server Name Indication]. Because of this, users may see false security warnings when they visit your SSL-secured websites.","“[_1]” is now the primary SSL host.":"“[_1]” is now the primary SSL host."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
