//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/js2/ssl/install-fi.js
// Module:    /jupiter/js2/ssl/install-fi
// Locale:    fi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"Toimet","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"Haluatko varmasti poistaa SSL-palvelimen [_1]? Tätä toimintoa ei voi kumota.","Certificate Expiration":"Varmenteen vanhentuminen","Confirm SSL Host Delete":"Vahvista SSL-palvelimen poisto","Deleting SSL host “[_1]” …":"Poistetaan SSL-palvelinta [_1]…","Document Root":"Tiedoston päätaso","Is Primary Website on IP Address?":"Onko ensisijainen verkkosivusto IP-osoitteessa?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"Onko verkon [output,acronym,SNI,Server Name Indication] tarpeen?","Loading …":"Ladataan…","No":"Ei","Setting “[_1]” as the primary SSL host …":"Setting “[_1]” as the primary SSL host …","The SSL host for “[_1]” has been removed.":"Kohteen [_1] SSL-palvelin on poistettu.","Yes":"Kyllä","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You don’t have a dedicated IP address. Browsers that were released before 2013 may not support [output,abbr,SNI,Server Name Indication]. Because of this, users may see false security warnings when they visit your SSL-secured websites.":"[output,strong,Note:] You don’t have a dedicated IP address. Browsers that were released before 2013 may not support [output,abbr,SNI,Server Name Indication]. Because of this, users may see false security warnings when they visit your SSL-secured websites.","“[_1]” is now the primary SSL host.":"“[_1]” is now the primary SSL host."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
