//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/autossl/views/select_provider_controller.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/autossl/views/select_provider_controller-vi.js
// Module:    /templates/autossl/views/select_provider_controller-vi
// Locale:    vi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"This interface uses the following parameters to calculate the usability score: [list_and,_1].":"This interface uses the following parameters to calculate the usability score: [list_and,_1].","You have configured [asis,AutoSSL] to use the “[_1]” provider.":"You have configured [asis,AutoSSL] to use the “[_1]” provider.","You have created a new registration for this system with “[_1]” and configured [asis,AutoSSL] to use that provider.":"You have created a new registration for this system with “[_1]” and configured [asis,AutoSSL] to use that provider.","You have disabled [asis,AutoSSL]. Any users with [asis,SSL] certificates from [asis,AutoSSL] will continue to use them, but the system will not automatically renew these certificates.":"You have disabled [asis,AutoSSL]. Any users with [asis,SSL] certificates from [asis,AutoSSL] will continue to use them, but the system will not automatically renew these certificates.","[output,em,Unspecified]":"[output,em,Unspecified]","[quant,_1,day,days]":"[quant,_1,ngày,ngày]","[quant,_1,hour,hours]":"[quant,_1,giờ,giờ]","[quant,_1,minute,minutes]":"[quant,_1,phút,phút]","[quant,_1,second,seconds]":"[quant,_1,giây,giây]","[quant,_1,year,years]":"[quant,_1,năm,năm]","unlimited":"không giới hạn"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
