<div class="section">
    <div class="row">
        <div class="col-xs-12">
            <item-lister
                id="domainItemLister"
                items="getFilteredDomains()"
                configuration-options="tableConfigurationOptions"
                header-items="tableHeaderItems">
                    <domain-lister-view></domain-lister-view>
            </item-lister>

        </div>

    </div>
</div>
