//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/ipv6/range.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/ipv6/range-hu.js
// Module:    /templates/ipv6/range-hu
// Locale:    hu
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Delete the “[_1]” range?":"Törli a(z) „[_1]” tartományt?","“[_1]” successfully added to the range list.":"„[_1]” hozzáadása a tartománylistához megtörtént.","“[_1]” successfully removed from the range list.":"„[_1]” eltávolítása a tartománylistából megtörtént."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
