//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/js2/cron/index.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/js2/cron/index-de.js
// Module:    /jupiter/js2/cron/index-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"AJAX-Fehler","Error":"Fehler","JSON parse failed.":"JSON-Analyse fehlgeschlagen.","Loading …":"Wird geladen…","Please refresh the page and try again.":"Bitte aktualisieren Sie die Seite und versuchen Sie es erneut.","less »":"weniger »"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
